/* ============================================================
   Innovation Week Oslo 2026 — trilingual content (NO / EN / ES)
   Values may contain inline HTML. Keys map to [data-i18n].
   ============================================================ */
window.I18N = {

/* ---------------------------------------------------------- NORSK */
no: {
  "doc.title": "Innovation Week Oslo 2026 — Lean Communications",
  "lang.label": "Språk",

  "nav.week": "Uka",
  "nav.friday": "Fredagen",
  "nav.ablokka": "A-blokka",
  "nav.bodo": "Bodø",
  "nav.method": "Metoden",
  "nav.tools": "Verktøy",
  "nav.about": "Om oss",
  "nav.cta": "Hold kontakten",

  "hero.eyebrow": "VDC Innovation Week · Oslo · 2.–5. juni 2026",
  "hero.langhint": "Denne oppsummeringen åpner på engelsk — bytt mellom NO / EN / ES / DE oppe til høyre når du vil.",
  "hero.title": "En uke i hvordan<br>Norge bygger — <span class=\"g\">sammen</span>",
  "hero.sub": "Til <b>MAS Digitales Bauen</b> ved FHNW — og vår gode venn fra Lima. Dette er en liten oppsummering av uka dere hadde i Oslo, og særlig ettermiddagen dere tilbrakte hos oss fredag 5. juni. Takk for at dere kom innom.",
  "hero.chipHostL": "Vert",
  "hero.chipHostV": "Øyvind Børstad · Lean Communications",
  "hero.chipWhenL": "Når",
  "hero.chipWhenV": "Fredag 5. juni, 13:30–15:30",
  "hero.chipWhereL": "Hvor",
  "hero.chipWhereV": "@Nordic Office of Architecture, Oslo",

  "week.eyebrow": "Hele uka",
  "week.title": "Fire dager i den norske<br>bygge­bransjens <span class=\"g\">verksted</span>",
  "week.lead": "Dere møtte hele kjeden — fra digitale produktdata og informasjonsleveranser, via store rådgivermiljøer og samlokalisering, til reelle prosjekter styrt med Lean og VDC. Akkurat det en master i Digitales Bauen handler om: å knytte modell, data og mennesker sammen til noe som faktisk lar seg bygge.",
  "week.d1.day": "Tirsdag 2. juni",
  "week.d1.tag": "Ankomst",
  "week.d1.title": "Velkommen til Oslo",
  "week.d1.body": "Ankomstdag og felles velkomstmiddag på <b>Frognerseteren</b>, det gamle tømmerhuset i skogen høyt over byen — med utsikt over hele Oslofjorden. En myk start før en tett faglig uke.",
  "week.d2.day": "Onsdag 3. juni",
  "week.d2.tag": "Data & informasjon",
  "week.d2.title": "Cobuilder · AnkerDB · VDC-konferanse",
  "week.d2.body": "<b>Cobuilder</b> om produktdata gjennom prosjektering, bygging og drift — det digitale produktpasset. <b>AnkerDB</b> om informasjonsleveranser i byggeprosjekter. Kvelden ble brukt på <b>VDC-konferansen</b> på Construction City — nettverk med norsk byggenæring.",
  "week.d3.day": "Torsdag 4. juni",
  "week.d3.tag": "Rådgivning & samlokalisering",
  "week.d3.title": "Skanska · COWI",
  "week.d3.body": "Besøk hos <b>Skanska</b> sitt hovedkontor, og hos <b>COWI</b> — et internasjonalt rådgivermiljø innen ingeniørfag, arkitektur, energi og miljø. Tema: samlokalisering og tverrfaglig prosjektering i praksis.",
  "week.d4.day": "Fredag 5. juni",
  "week.d4.tag": "Lean & VDC i praksis",
  "week.d4.title": "Bane NOR · COWI · Lean Communications",
  "week.d4.body": "Prosjektbesøk på infrastruktur med <b>Bane NOR</b> (Kolbotn stasjon), samlokalisering hos COWI — og til slutt ettermiddagen hos <b>oss</b>. Det er den vi har skrevet ned her.",
  "week.relevance": "Hvorfor dette angår dere: en master i Digitales Bauen er bindeleddet mellom modellen og byggeplassen. Alt dere så denne uka — produktdata, informasjonsleveranser, samlokalisering, samspill — er biter av det samme bildet: å gjøre digital informasjon til bygde kvadratmeter, uten å miste menneskene på veien.",

  "friday.eyebrow": "Fredag · 13:30–15:30",
  "friday.title": "Ettermiddagen <span class=\"g\">hos oss</span>",
  "friday.lead": "Vi tok dere gjennom fem ting på halvannen time. Her er de — og resten av siden følger den samme rekkefølgen, så du kan lese videre i ditt eget tempo.",
  "friday.a1": "Samspill i Norge — slik har bransjen lært seg å bygge sammen",
  "friday.a2": "A-blokka — IPD i praksis",
  "friday.a3": "Nye Bodø lufthavn — verktøykassa fra utviklingsfasen",
  "friday.a4": "Metoden og verktøyene vi bruker",
  "friday.a5": "Folka — det viktigste til slutt",

  "samspill.eyebrow": "Samspill i Norge",
  "samspill.title": "Slik jobbet vi før.<br>Slik jobber vi <span class=\"g\">nå</span>.",
  "samspill.lead": "For tjue år siden ble bygg stort sett tegnet ferdig, priset og satt ut på anbud — hver part optimaliserte sin egen bit. I dag bygger de beste prosjektene laget først, og bygget etterpå. Det er den utviklingen vi viste dere.",
  "samspill.thenL": "For ~20 år siden",
  "samspill.then1": "Sekvensiell prosess: prosjekter ble tegnet, priset og satt ut i tur og orden.",
  "samspill.then2": "Kontrakter satte partene opp mot hverandre — hver optimaliserte sin del.",
  "samspill.then3": "Feil og kollisjoner ble oppdaget på bygge­plassen, der de er dyrest å rette.",
  "samspill.then4": "Framdrift var noe man rapporterte på — ikke noe man styrte i sanntid.",
  "samspill.nowL": "Slik jobber vi i dag",
  "samspill.now1": "Tidlig involvering: byggherre, entreprenør og rådgivere utvikler løsningen sammen.",
  "samspill.now2": "Samspills- og IPD-kontrakter med felles mål, delt risiko og delt gevinst.",
  "samspill.now3": "Tverrfaglige team som løser problemene samtidig, i Big Room, før produksjon.",
  "samspill.now4": "Framdrift bygd som et produksjonssystem — takt, planlagt og kontrollert.",
  "samspill.ipdTitle": "Den norske samspillsmodellen — IPD",
  "samspill.ipd0L": "Anskaffelse",
  "samspill.ipd0": "Byggherren velger entreprenør og rådgivere til samspillet — på kompetanse og holdning, ikke laveste pris alene.",
  "samspill.ipd1L": "Utvikling — som ett lag",
  "samspill.ipd1": "Byggherre, entreprenør og fag utvikler løsningen sammen, samlokalisert, og blir enige om en målpris før byggingen starter.",
  "samspill.ipd1tag": "8–15 måneder samlokalisert",
  "samspill.ipd2L": "Gjennomføring — som ett lag",
  "samspill.ipd2": "Bygging på samme målpris, med delt risiko og delt gevinst. Bonus er gulrot, ikke straff — alle tjener på at helheten lykkes.",
  "samspill.ipd2tag": "Delt risiko og gevinst",
  "samspill.ipdQuote": "Godt samarbeid oppstår ikke av seg selv — det planlegges.",

  "ablokka.eyebrow": "Prosjekt 1 · A-blokka, nytt regjeringskvartal",
  "ablokka.title": "Et bygg der kvalitet, kostnad<br>og tid ble <span class=\"g\">utviklet</span>, ikke gjettet",
  "ablokka.lead": "A-blokka (K204) i det nye regjeringskvartalet i Oslo er et IPD-prosjekt der entreprenøren HENT, byggherren Statsbygg og fagene utviklet løsningen sammen. Vi fortalte historien om hvordan prosjektet ble drevet med jernhardt fokus på kvalitet, kostnad og tid — og hvordan kontrakten gjorde det mulig.",
  "ablokka.s1v": "3,2 mrd",
  "ablokka.s1t": "målpris (NOK) for K204 — kalkylen ble utviklet som levende tall mot denne",
  "ablokka.s2v": "20+",
  "ablokka.s2t": "kontrollområder i produksjon samtidig, styrt med taktplanlegging",
  "ablokka.s3v": "Okt 2025",
  "ablokka.s3t": "bygget ferdigstilt og overlevert i oktober 2025 — én måned før planen; innflytting fra januar 2026",
  "ablokka.bigroomCap": "Fra den digitale Big Room-tavla for A-blokka K204: framdriftsplaner, operativt og kontraktuelt organisasjonskart, modenhetsvurdering, planpålitelighet og den dynamiske kalkylen — alt på ett sted, levende.",
  "ablokka.photo1": "Slipp inn ditt eget bilde fra A-blokka / regjeringskvartalet",
  "ablokka.photo2": "Slipp inn et bilde fra prosjektbesøket",
  "ablokka.illTitle": "Tre ting vi viste fra A-blokka",
  "ablokka.ill1L": "Organisasjonsmodell",
  "ablokka.ill1cap": "Sirkulær modell med tverrfaglige scrum-team rundt prosjektet i sentrum — ikke et hierarki, men et hjul.",
  "ablokka.illOrgCenter": "Prosjektet",
  "ablokka.illOrgK1": "Samspillsledelse",
  "ablokka.illOrgK2": "Faggrupper",
  "ablokka.illOrgK3": "Prosessgrupper",
  "ablokka.ill2L": "Kalkyle &amp; modenhet",
  "ablokka.ill2cap": "Kostnaden utvikles ned mot målpris mens løsningenes modenhet stiger — to kurver som møtes.",
  "ablokka.illCalcK1": "Kalkyle",
  "ablokka.illCalcK2": "Målpris",
  "ablokka.illCalcK3": "Modenhet",
  "ablokka.ill3L": "Taktplan",
  "ablokka.ill3cap": "Én felles takt for prosjektering, produksjon og systematisk ferdigstillelse — fag etter fag gjennom hvert kontrollområde.",
  "ablokka.illTaktP1": "Prosjektering",
  "ablokka.illTaktP2": "Produksjon",
  "ablokka.illTaktP3": "Ferdigstillelse",
  "ablokka.shotCap": "A-blokka i det nye regjeringskvartalet, sett ved skumring.",
  "ablokka.resEyebrow": "Fase 2 produksjon · resultater ved overlevering",
  "ablokka.resLead": "Måten å jobbe på ga ikke bare bedre samarbeid — den ga målbare resultater på det som teller: tid, kostnad og kvalitet.",
  "ablokka.res1V": "100 %",
  "ablokka.res1L": "Milepæler levert",
  "ablokka.res1S": "Hver eneste milepæl nådd",
  "ablokka.res2V": "1 mnd",
  "ablokka.res2L": "Foran plan",
  "ablokka.res2S": "Overlevert tidligere enn planlagt",
  "ablokka.res3V": "3 %",
  "ablokka.res3L": "Under budsjett",
  "ablokka.res3S": "Disiplinert kostnadsstyring",
  "ablokka.res4V": "14",
  "ablokka.res4L": "Endringsordrer",
  "ablokka.res4S": "Alle avklart før overlevering",
  "ablokka.resQuote": "Forutsigbarhet skapes — den kommer ikke av seg selv.",

  "aahka.eyebrow": "A-blokka · Den skrå veggen",
  "aahka.title": "AAhkA — hele Norge<br>samlet i <span class=\"g\">ett kunstverk</span>",
  "aahka.lead": "Rett innenfor hovedinngangen i A-blokka ligger Pyramiderommet. Den store, skråstilte veggen ba nærmest om et kunstverk — og fikk det. <b>AAhkA</b> av den samisk-finske kunstneren <b>Outi Pieski</b> er over 51 meter høyt og dekker mer enn 700 kvadratmeter. For mange blir det det aller første møtet med det nye regjeringskvartalet.",
  "aahka.b1": "Verket er en integrert del av den trekantede, skrå veggflaten, bygget opp av sammenføyde bjørkespiler i ulike retninger — noen trehvite, andre malt, forgylt eller skåret med ornamenter. Det trer fram som et relieff i veggens egen topografi.",
  "aahka.b2": "AAhkA viser en kvinne i halvprofil med den samiske hornlua <i>ládjogahpir</i>, messingringer på fingrene og en mønstret vandrestav — alt knyttet til <i>duodji</i>, samisk kunsthåndverk, der prosessen er like viktig som det ferdige verket.",
  "aahka.b3": "Tittelen viser til Moder Jord som juridisk person — en beskytter av naturen, en påminnelse om at mennesket og naturen står i et likeverdig forhold. Veggens glassfasade gjør at verket også sees fra utsiden, som en del av bybildet.",
  "aahka.tieIn": "Hvorfor vi tok dere hit: et kunstverk på 700 m², integrert i en skråvegg, montert på tre måneder midt i et stramt taktstyrt byggeprosjekt — det er samspill mellom arkitekt, kunstner og entreprenør i sin reneste form. «Det er ikke ofte entreprenøren får være med å bygge et kunstverk,» som HENT selv sa.",
  "aahka.fact1L": "Høyde",
  "aahka.fact1V": "51 m",
  "aahka.fact2L": "Flate",
  "aahka.fact2V": "700+ m²",
  "aahka.fact3L": "Montering",
  "aahka.fact3V": "3 måneder",
  "aahka.fact4L": "Kunstner",
  "aahka.fact4V": "Outi Pieski",
  "aahka.photo": "Slipp inn ditt bilde av AAhkA i Pyramiderommet",
  "aahka.src": "Kilder: KORO (Kunst i offentlige rom), Store norske leksikon, Arkitektur.no. AAhkA ble avduket høsten 2025.",

  "bodo.eyebrow": "Prosjekt 2 · Nye Bodø lufthavn",
  "bodo.title": "Den samme tankegangen,<br>løftet til en hel <span class=\"g\">flyplass</span>",
  "bodo.lead": "Så hoppet vi til Bodø. Nye Bodø lufthavn flyttes ~900 meter, frigjør en helt ny bydel, og bygges som en samspillskontrakt mellom Avinor og entreprenørene. Mye gjøres likt med A-blokka — men her gikk vi dypere inn i selve verktøykassa fra utviklingsfasen.",
  "bodo.s1v": "2,4 mrd",
  "bodo.s1t": "målpris (eks. mva) for nytt terminal- og driftsbygg — samspillskontrakt med Avinor",
  "bodo.s2v": "~27 000 m²",
  "bodo.s2t": "terminal og driftsbygg (HENT) i en totalentreprise med samspill",
  "bodo.s3v": "2029/30",
  "bodo.s3t": "planlagt åpning; utviklingsfase og målpris før spaden settes i jorda",
  "bodo.heroCap": "Nye Bodø lufthavn — illustrasjon, Team NLBO.",
  "bodo.tpTitle": "Slik defineres målprisen — og hva som skjer over eller under den",
  "bodo.tpSeg1": "Selvkost",
  "bodo.tpSeg2": "Risiko og muligheter",
  "bodo.tpSeg3": "Påslag og fortjeneste",
  "bodo.tpBuildNote": "Alle tre delene er synlige for partene. Når løsningene modnes, faller usikkerheten — og målprisen blir et tall man kan stole på.",
  "bodo.tpB3L": "Målpris",
  "bodo.tpAxisY": "Kostnad",
  "bodo.tpAxisX": "Tid →",
  "bodo.tpDev": "Utviklingsfase",
  "bodo.tpFinal": "Sluttkostnad",
  "bodo.tpCap": "Tak",
  "bodo.tpFloor": "Gulv",
  "bodo.tpZoneRisk": "Risiko deles",
  "bodo.tpZoneOpp": "Muligheter deles",
  "bodo.tpSave": "Besparelse",
  "bodo.goalsTitle": "NLBO — målsettinger ved overlevering",
  "bodo.gSHA": "SHA",
  "bodo.gSHA1": "Null skader",
  "bodo.gCost": "Kostnad",
  "bodo.gCost1": "NOK 2,4 mrd eks. mva",
  "bodo.gCost2": "«Slå» målprisen",
  "bodo.gQual": "Kvalitet",
  "bodo.gQual1": "Ingen vesentlige feil ved overlevering",
  "bodo.gTime": "Tid",
  "bodo.gTime1": "ICT ferdig: 01.05.28",
  "bodo.gTime2": "MC: 01.12.27",
  "bodo.gTime3": "Overlevering: 01.06.28",
  "bodo.samspillNote": "Samspill betyr at byggherre og entreprenør først går gjennom en <b>utviklingsfase</b> sammen — optimaliserer løsninger, kvantifiserer usikkerhet og blir enige om en <b>målpris</b> — før selve byggingen starter. Det er der de store grepene tas.",

  "org.eyebrow": "Metoden · Organisasjon",
  "org.title": "Samspills<span class=\"g\">hjulet</span>",
  "org.lead": "Vi gikk gjennom organisasjonsmodellen vår: tverrfaglige team rundt et felles sentrum, alle med samme oppgave — å optimalisere helheten i prosjektet. Ingen pyramide. Et hjul, der fagene møtes på midten.",
  "org.hub": "Tverrfaglige<br>samspillsteam",
  "org.t1": "Råbygg",
  "org.t2": "Fasade & tak",
  "org.t3": "Innredning",
  "org.t4": "Tekniske fag",
  "org.t5": "Prosjektering",
  "org.t6": "Innkjøp",
  "org.t7": "Produksjon",
  "org.t8": "BIM / VDC",
  "org.caption": "Beveg pekeren over et team for å se det løftes fram. Hvert team eier sin bit, men jobber mot samme sentrum.",
  "embed.kicker": "Prøv selv",
  "embed.title": "Kjernen i VDC-motoren",
  "embed.lead": "Tre ting utgjør kjernen i VDC-motoren. Klikk deg gjennom hver av dem i den interaktive modellen under — eller åpne den i fullskjerm.",
  "embed.open": "Åpne i fullskjerm",
  "embed.close": "Lukk",
  "embed.p1L": "Organisering",
  "embed.p1": "Sirkelen, ikke pyramiden. Prosjektet i sentrum, med tverrfaglige team rundt — beslutninger tas der arbeidet gjøres.",
  "embed.p2L": "Planverk & takt",
  "embed.p2": "Én felles takt for prosjektering, produksjon og systematisk ferdigstillelse — alle fag i samme rytme.",
  "embed.p3L": "Kalkyle & risiko",
  "embed.p3": "Kalkylen utvikles etter modenhet, og risiko styres før den treffer bygget — mot en trygg målpris.",
  "embed.popen": "Åpne modulen",
  "embed.whyTitle": "Hvorfor sirkel slår pyramide",
  "embed.tradL": "Tradisjonell hierarkisk modell",
  "embed.trad1": "Beslutninger tas på toppen — de som vet mest blir hørt sist.",
  "embed.trad2": "Hvert fag optimaliserer sin egen silo, ikke helheten.",
  "embed.trad3": "Informasjon når bunnen sent — feil dukker opp på bygget.",
  "embed.trad4": "Lange beslutningsveier gir treg respons når noe endrer seg.",
  "embed.wheelL": "Samspillshjulet",
  "embed.wheel1": "Alle team jobber mot det samme målet i sentrum.",
  "embed.wheel2": "Tverrfaglige beslutninger tas der arbeidet faktisk gjøres.",
  "embed.wheel3": "Premissrådgivere hentes på pull — riktig kompetanse til rett tid.",
  "embed.wheel4": "Kort vei mellom fagene gir rask, felles respons.",

  "cost.eyebrow": "Metoden · Kostnad",
  "cost.title": "Kostnad utvikles på<br><span class=\"g\">to prinsipper</span>",
  "cost.lead": "Kostnaden i prosjektet gjettes ikke. Den utvikles, beslutning for beslutning, ved å spørre om hver løsning gjør to ting:",
  "cost.p1L": "Reduser risiko",
  "cost.p1": "Velg løsninger som tar usikkerhet ut av prosjektet — det som kan gå galt, koster alltid mest.",
  "cost.p2L": "Øk modenhet",
  "cost.p2": "Løft løsningene fra skisse til ferdig, besluttet underlag — modenhet er det som gjør pris til noe man kan stole på.",
  "cost.sum": "Og alt henger sammen i én konsekvens: <b>tid</b>. Reduserer du risiko og øker modenhet, faller framdriften på plass. Klarer du det ikke, betaler du i tid — og tid er den dyreste valutaen i et byggeprosjekt.",

  "takt.eyebrow": "Metoden · Framdrift",
  "takt.title": "Framdriftsplaner bygd som<br><span class=\"g\">produksjonssystemer</span>",
  "takt.lead": "I begge prosjektene er framdriften bygd som et produksjonssystem — taktplanlegging og taktkontroll. Arbeidet deles i like store kontrollområder, og fagene går gjennom dem i fast rytme: betong, tømmer, rør, ventilasjon, elektro — som et tog gjennom stasjoner.",
  "takt.legendArea": "Loddrett: kontrollområder (lokasjoner og faser)",
  "takt.legendTrain": "Vannrett: tid — fagene flytter seg én lokasjon per takt",
  "takt.cars": ["Betong","Tømmer","Rør","Ventilasjon","Elektro"],
  "takt.locs": ["KO-01 · Grunn","KO-02 · Plan 1","KO-03 · Plan 2","KO-04 · Plan 3","KO-05 · Tak & teknikk","KO-06 · Fasade"],
  "takt.caption": "En forenklet takt: hvert fag følger etter det forrige i fast rytme gjennom kontrollområdene. Forutsigbart for alle — og lett å se når noe glipper.",
  "takt.note": "På A-blokka ble prosjektering, forberedende tog og innredningstog koblet til den samme takten, med ferdig arbeidsunderlag seks uker før hvert kontrollområde startet.",

  "people.eyebrow": "Det viktigste",
  "people.q": "Alle metoder og all teknologi gir null verdi uten at du får med deg folka. De er ALLTID viktigst.",
  "people.body": "Begge prosjektene hadde tungt fokus på teamutvikling og trening av folka i prosjektet. Det er kontakten mellom mennesker som får prosjekter bygd — og som gjør prosjekter i verdensklasse mulige. Modeller, takt og kalkyler er bare verktøy. Verdien ligger i hendene og hodene som bruker dem.",

  "tools.eyebrow": "Verktøy vi bruker — og deler",
  "tools.title": "Verktøyene vi <span class=\"g\">viste dere</span>",
  "tools.lead": "Alt vi viste er gratis å bruke. Her er lenkene — prøv dem gjerne på et eget prosjekt.",
  "tools.c1L": "Gratis digitale verktøy",
  "tools.c1": "Åtte små, gratis verktøy bygd på vår lange erfaring — hvert løser ett konkret problem i prosjekthverdagen.",
  "tools.c1cta": "Se de digitale verktøyene",
  "tools.c2L": "Taktplan",
  "tools.c2": "Vårt egenutviklede verktøy for taktplanlegging og -kontroll.",
  "tools.c2cta": "Åpne Taktplan",
  "tools.c3L": "Hørt om VDC?",
  "tools.c3": "Et kort, gratis introduksjonskurs til VDC — en fin start.",
  "tools.c3cta": "Ta kurset",
  "tools.coursesL": "Opplæringsprogrammer",
  "tools.courses": "Kursene våre er <b>gratis</b> og finnes på <b>norsk, engelsk og spansk</b>. Registrer deg og logg på (f.eks. med Google), så er du i gang.",
  "tools.coursescta": "Se alle kurs",

  "about.eyebrow": "Om oss",
  "about.title": "Hvem dere tilbrakte<br>ettermiddagen <span class=\"g\">med</span>",
  "about.lead": "Lean Communications er et lite konsulentselskap. Vi gjør to ting: vi utvikler kompetansen til folk i bygg- og anleggsbransjen, og vi leder komplekse byggeprosjekter. Ofte begge deler samtidig — for det er nettopp i de virkelige prosjektene kompetansen fester seg.",
  "about.c1L": "Kompetanse­utvikling",
  "about.c1": "Kurs, opplæring og trening i Lean og VDC — for hele organisasjonen, ikke bare ledelsen.",
  "about.c2L": "Prosjektledelse",
  "about.c2": "Vi går inn i virkelige, komplekse byggeprosjekter og hjelper dem å implementere Lean og VDC i praksis.",
  "about.pmNum": "15",
  "about.pmNumL": "prosjektledere, 100 % ute i reelle prosjekter",
  "about.pm1": "I tillegg har vi ansatt <b>15 prosjektledere</b> som jobber 100 % ute i prosjekter — som prosjektledere, prosjekteringsledere, framdriftsplanleggere, prosjektstyrere, kultur- og teamutviklere og mer.",
  "about.pmR1": "Prosjektledere",
  "about.pmR2": "Prosjekteringsledere",
  "about.pmR3": "Framdriftsplanleggere",
  "about.pmR4": "Prosjektstyrere",
  "about.pmR5": "Kultur- og teamutviklere",
  "about.pm2": "Gjennom denne kontakten med reelle prosjekter bygger vi erfaringen og kompetansen rett inn i nye opplærings- og kompetanseprodukter — slik at det blir enda bedre prosjekter, både i Norge og i utlandet.",

  "cta.eyebrow": "Takk for besøket",
  "cta.title": "Lykke til videre med<br>Digitales Bauen",
  "cta.lead": "Det var en glede å ha dere her. Ta gjerne med dere én ting: verktøyene er like for alle — det er folka som gjør forskjellen. Hold kontakten, og si fra hvis dere er innom Oslo igjen. Ølet står klart.",
  "cta.o1L": "Kursene",
  "cta.o1": "Gratis, på tre språk. Begynn med «Hørt om VDC?».",
  "cta.o1f": "leancommunications.no",
  "cta.o2L": "Verktøyene",
  "cta.o2": "De digitale verktøyene og Taktplan — prøv dem på et eget prosjekt.",
  "cta.o2f": "Digitale verktøy",
  "cta.o3L": "Oss",
  "cta.o3": "Øyvind og resten av gjengen i Lean Communications.",
  "cta.o3f": "Ta kontakt",

  "footer.tag": "Norges største aktør for opplæring innen Lean og VDC til bygg- og anleggsbransjen. Samarbeider med NTNU. Kontorer i Oslo og Bergen.",
  "footer.note": "En oppsummering laget til MAS Digitales Bauen (FHNW) etter VDC Innovation Week i Oslo, juni 2026. Prosjektfakta fra A-blokka K204 (regjeringskvartalet) og Nye Bodø lufthavn. Kunstverk: AAhkA av Outi Pieski (KORO)."
},

/* ---------------------------------------------------------- ENGLISH */
en: {
  "doc.title": "Innovation Week Oslo 2026 — Lean Communications",
  "lang.label": "Language",

  "nav.week": "The week",
  "nav.friday": "Friday",
  "nav.ablokka": "A-Block",
  "nav.bodo": "Bodø",
  "nav.method": "The method",
  "nav.tools": "Tools",
  "nav.about": "About",
  "nav.cta": "Keep in touch",

  "hero.eyebrow": "VDC Innovation Week · Oslo · 2–5 June 2026",
  "hero.langhint": "This recap defaults to English — switch between NO / EN / ES / DE at the top right whenever you like.",
  "hero.title": "A week inside how<br>Norway builds — <span class=\"g\">together</span>",
  "hero.sub": "For the <b>MAS Digitales Bauen</b> students at FHNW — and our good friend from Lima. This is a short recap of your week in Oslo, and especially the afternoon you spent with us on Friday 5 June. Thanks for stopping by.",
  "hero.chipHostL": "Host",
  "hero.chipHostV": "Øyvind Børstad · Lean Communications",
  "hero.chipWhenL": "When",
  "hero.chipWhenV": "Friday 5 June, 13:30–15:30",
  "hero.chipWhereL": "Where",
  "hero.chipWhereV": "@Nordic Office of Architecture, Oslo",

  "week.eyebrow": "The whole week",
  "week.title": "Four days inside the<br>workshop of Norwegian <span class=\"g\">construction</span>",
  "week.lead": "You met the whole chain — from digital product data and information delivery, through large consultancies and co-location, to real projects run with Lean and VDC. Exactly what a master's in Digitales Bauen is about: tying model, data and people into something that can actually be built.",
  "week.d1.day": "Tuesday 2 June",
  "week.d1.tag": "Arrival",
  "week.d1.title": "Welcome to Oslo",
  "week.d1.body": "Arrival day and a welcome dinner at <b>Frognerseteren</b>, the old timber lodge in the forest high above the city — with the whole Oslo fjord at your feet. A soft start before a dense week.",
  "week.d2.day": "Wednesday 3 June",
  "week.d2.tag": "Data & information",
  "week.d2.title": "Cobuilder · AnkerDB · VDC conference",
  "week.d2.body": "<b>Cobuilder</b> on product data across design, construction and operation — the digital product passport. <b>AnkerDB</b> on information delivery for construction projects. The evening went to the <b>VDC conference</b> at Construction City — networking with Norwegian industry.",
  "week.d3.day": "Thursday 4 June",
  "week.d3.tag": "Consulting & co-location",
  "week.d3.title": "Skanska · COWI",
  "week.d3.body": "A visit to <b>Skanska's</b> head office, and to <b>COWI</b> — an international consultancy in engineering, architecture, energy and environment. The theme: co-location and multidisciplinary design in practice.",
  "week.d4.day": "Friday 5 June",
  "week.d4.tag": "Lean & VDC in practice",
  "week.d4.title": "Bane NOR · COWI · Lean Communications",
  "week.d4.body": "An infrastructure project visit with <b>Bane NOR</b> (Kolbotn station), co-location at COWI — and finally the afternoon with <b>us</b>. That's the one we've written down here.",
  "week.relevance": "Why it matters to you: a master in Digitales Bauen is the link between the model and the muddy site. Everything you saw this week — product data, information delivery, co-location, collaboration — is part of the same picture: turning digital information into built square metres without losing the people along the way.",

  "friday.eyebrow": "Friday · 13:30–15:30",
  "friday.title": "The afternoon <span class=\"g\">with us</span>",
  "friday.lead": "We took you through five parts. First, a little on how Norway works together on building projects — then and now. Then two real projects, the tools we use, and the most important thing of all at the end: the people.",
  "friday.a1": "The A-Block — insight into IPD in Norway",
  "friday.a2": "New Bodø Airport — collaborative contract, tools and methods in the development phase",
  "friday.a3": "AI tools",
  "friday.a4": "Workshop — Innovation Week in Oslo, key takeaways",
  "friday.a5": "The A-Block — project visit",

  "samspill.eyebrow": "Collaboration in Norway",
  "samspill.title": "How we worked then.<br>How we work <span class=\"g\">now</span>.",
  "samspill.lead": "Twenty years ago buildings were mostly drawn, priced and tendered — each party optimising its own slice. Today the best projects build the team first, and the building afterwards. That's the journey we walked you through.",
  "samspill.thenL": "~20 years ago",
  "samspill.then1": "Sequential process: projects were drawn, priced and tendered one step at a time.",
  "samspill.then2": "Contracts set the parties against each other — each optimised its own part.",
  "samspill.then3": "Errors and clashes surfaced on site, where they cost the most to fix.",
  "samspill.then4": "Progress was something you reported on — not something you steered in real time.",
  "samspill.nowL": "How we work today",
  "samspill.now1": "Early involvement: client, contractor and consultants develop the solution together.",
  "samspill.now2": "Collaborative / IPD contracts with shared goals, shared risk and shared reward.",
  "samspill.now3": "Cross-functional teams solving problems concurrently, in a Big Room, before production.",
  "samspill.now4": "Progress built as a production system — takt, planned and controlled.",
  "samspill.ipdTitle": "The Norwegian collaboration model — IPD",
  "samspill.ipd0L": "Procurement",
  "samspill.ipd0": "The client selects contractor and consultants for the collaboration — on competence and attitude, not lowest price alone.",
  "samspill.ipd1L": "Development — as one team",
  "samspill.ipd1": "Client, contractor and disciplines develop the solution together, co-located, and agree a target price before construction starts.",
  "samspill.ipd1tag": "8–15 months co-located",
  "samspill.ipd2L": "Execution — as one team",
  "samspill.ipd2": "Building on the same target price, with shared risk and shared reward. Bonus is a carrot, not a stick — everyone gains when the whole succeeds.",
  "samspill.ipd2tag": "Shared risk & reward",
  "samspill.ipdQuote": "Collaboration is designed — it is not left to chance.",

  "ablokka.eyebrow": "Project 1 · The A-Block, new government quarter",
  "ablokka.title": "A building where quality, cost<br>and time were <span class=\"g\">developed</span>, not guessed",
  "ablokka.lead": "The A-Block (K204) in Oslo's new government quarter is an IPD project where the contractor HENT, the client Statsbygg and the disciplines developed the solution together. We told the story of how the project was run with a relentless focus on quality, cost and time — and how the contract made it possible.",
  "ablokka.s1v": "3.2 bn",
  "ablokka.s1t": "target price (NOK) for K204 — the estimate was developed as a living number toward it",
  "ablokka.s2v": "20+",
  "ablokka.s2t": "control areas in production at the same time, run with takt planning",
  "ablokka.s3v": "Oct 2025",
  "ablokka.s3t": "the designed building handed over in October 2025 — one month ahead of plan; move-in from January 2026",
  "ablokka.bigroomCap": "From the A-Block K204 digital Big Room board: progress plans, operational and contractual org charts, maturity assessment, plan reliability and the dynamic estimate — all in one place, all alive.",
  "ablokka.photo1": "Drop in your own photo from the A-Block / government quarter",
  "ablokka.photo2": "Drop in a photo from the project visit",
  "ablokka.illTitle": "Three things we showed from the A-Block",
  "ablokka.ill1L": "Organisation model",
  "ablokka.ill1cap": "A circular model with cross-functional scrum teams around the project at the centre — not a hierarchy, but a wheel.",
  "ablokka.illOrgCenter": "The project",
  "ablokka.illOrgK1": "Collaboration lead",
  "ablokka.illOrgK2": "Discipline teams",
  "ablokka.illOrgK3": "Process teams",
  "ablokka.ill2L": "Cost &amp; maturity",
  "ablokka.ill2cap": "Cost is developed down toward the target price while the maturity of the solutions rises — two curves that meet.",
  "ablokka.illCalcK1": "Estimate",
  "ablokka.illCalcK2": "Target price",
  "ablokka.illCalcK3": "Maturity",
  "ablokka.ill3L": "Takt plan",
  "ablokka.ill3cap": "One shared takt for design, production and systematic completion — trade after trade through each control area.",
  "ablokka.illTaktP1": "Design",
  "ablokka.illTaktP2": "Production",
  "ablokka.illTaktP3": "Completion",
  "ablokka.shotCap": "The A-Block in Oslo's new government quarter, at dusk.",
  "ablokka.resEyebrow": "Phase 2 production · results at handover",
  "ablokka.resLead": "The integrated approach didn't just improve collaboration — it produced measurable, extraordinary outcomes across every dimension.",
  "ablokka.res1V": "100%",
  "ablokka.res1L": "Milestones delivered",
  "ablokka.res1S": "Every single milestone met",
  "ablokka.res2V": "1 mo",
  "ablokka.res2L": "Ahead of schedule",
  "ablokka.res2S": "Completed early",
  "ablokka.res3V": "3%",
  "ablokka.res3L": "Below budget",
  "ablokka.res3S": "Disciplined cost control",
  "ablokka.res4V": "14",
  "ablokka.res4L": "Change orders",
  "ablokka.res4S": "All agreed before handover",
  "ablokka.resQuote": "Predictability is designed — not hoped for.",

  "aahka.eyebrow": "The A-Block · The slanted wall",
  "aahka.title": "AAhkA — all of Norway<br>gathered in <span class=\"g\">one artwork</span>",
  "aahka.lead": "Just inside the main entrance of the A-Block lies the Pyramid Room. The large, slanted wall practically asked for a work of art — and got one. <b>AAhkA</b> by the Sámi-Finnish artist <b>Outi Pieski</b> stands over 51 metres tall and covers more than 700 square metres. For many it will be the very first encounter with the new government quarter.",
  "aahka.b1": "The work is an integrated part of the triangular, slanted wall surface, built from joined birch slats laid in different directions — some left bare, others painted, gilded or carved with ornament. It emerges as a relief within the wall's own topography.",
  "aahka.b2": "AAhkA shows a woman in half-profile wearing the Sámi horn cap <i>ládjogahpir</i>, brass rings on her fingers and a patterned walking staff — all tied to <i>duodji</i>, Sámi craft, where the process matters as much as the finished work.",
  "aahka.b3": "The title refers to Mother Earth as a legal person — a protector of nature, a reminder that humans and nature stand in an equal relationship. The wall's glass façade means the work is seen from the outside too, as part of the cityscape.",
  "aahka.tieIn": "Why we brought you here: a 700 m² artwork, integrated into a slanted wall, mounted in three months in the middle of a tightly takt-controlled build — that's collaboration between architect, artist and contractor at its purest. \"It's not often a contractor gets to help build a work of art,\" as HENT put it.",
  "aahka.fact1L": "Height",
  "aahka.fact1V": "51 m",
  "aahka.fact2L": "Surface",
  "aahka.fact2V": "700+ m²",
  "aahka.fact3L": "Mounting",
  "aahka.fact3V": "3 months",
  "aahka.fact4L": "Artist",
  "aahka.fact4V": "Outi Pieski",
  "aahka.photo": "Drop in your photo of AAhkA in the Pyramid Room",
  "aahka.src": "Sources: KORO (Public Art Norway), Store norske leksikon, Arkitektur.no. AAhkA was unveiled in autumn 2025.",

  "bodo.eyebrow": "Project 2 · New Bodø Airport",
  "bodo.title": "The same thinking,<br>scaled up to a whole <span class=\"g\">airport</span>",
  "bodo.lead": "Then we jumped to Bodø. The new airport is being moved ~900 metres, freeing up a whole new district, and built as a collaborative contract between Avinor and the contractors. Much is done as on the A-Block — but here we went deeper into the actual toolbox from the development phase.",
  "bodo.s1v": "2.4 bn",
  "bodo.s1t": "target price (NOK excl. VAT) for the new terminal and operations buildings — collaborative contract with Avinor",
  "bodo.s2v": "~27,000 m²",
  "bodo.s2t": "terminal and operations buildings (HENT) in a design-build with collaboration",
  "bodo.s3v": "2029/30",
  "bodo.s3t": "planned opening; development phase and target price before breaking ground",
  "bodo.heroCap": "New Bodø Airport — render, Team NLBO.",
  "bodo.tpTitle": "How the target price is defined — and what happens above or below it",
  "bodo.tpSeg1": "Net cost",
  "bodo.tpSeg2": "Risk & opportunity",
  "bodo.tpSeg3": "Overhead & profit",
  "bodo.tpBuildNote": "All three parts are visible to the parties. As the solutions mature, uncertainty falls — and the target price becomes a number you can trust.",
  "bodo.tpB3L": "Target price",
  "bodo.tpAxisY": "Cost",
  "bodo.tpAxisX": "Time →",
  "bodo.tpDev": "Development phase",
  "bodo.tpFinal": "Final cost",
  "bodo.tpCap": "Cap",
  "bodo.tpFloor": "Floor",
  "bodo.tpZoneRisk": "Risk shared",
  "bodo.tpZoneOpp": "Opportunity shared",
  "bodo.tpSave": "Saving",
  "bodo.goalsTitle": "NLBO — result goals at handover",
  "bodo.gSHA": "HSE",
  "bodo.gSHA1": "Zero injuries",
  "bodo.gCost": "Cost",
  "bodo.gCost1": "NOK 2.4 bn excl. VAT",
  "bodo.gCost2": "«Beat» the target price",
  "bodo.gQual": "Quality",
  "bodo.gQual1": "No significant defects at handover",
  "bodo.gTime": "Time",
  "bodo.gTime1": "ICT complete: 01.05.28",
  "bodo.gTime2": "MC: 01.12.27",
  "bodo.gTime3": "Handover: 01.06.28",
  "bodo.samspillNote": "Collaboration (samspill) means client and contractor first go through a <b>development phase</b> together — optimising solutions, quantifying uncertainty and agreeing a <b>target price</b> — before construction starts. That's where the big moves are made.",

  "org.eyebrow": "Tool 1 · Organisation",
  "org.title": "The <span class=\"g\">circular</span> model",
  "org.lead": "We detailed the organisation plan: cross-functional scrum teams around a shared centre, all with the same job — to optimise the project as a whole. No pyramid. A circle, where the disciplines meet in the middle.",
  "org.hub": "Cross-functional<br>collaboration teams",
  "org.t1": "Structure",
  "org.t2": "Façade & roof",
  "org.t3": "Fit-out",
  "org.t4": "MEP / technical",
  "org.t5": "Design",
  "org.t6": "Procurement",
  "org.t7": "Production",
  "org.t8": "BIM / VDC",
  "org.caption": "Hover over a team to see it lift forward. Each team owns its slice, but works toward the same centre.",
  "embed.kicker": "Try it yourself",
  "embed.title": "The core of the VDC engine",
  "embed.lead": "Three things make up the core of the VDC engine. Click through each of them in the interactive model below — or open it full screen.",
  "embed.open": "Open full screen",
  "embed.close": "Close",
  "embed.p1L": "Organisation",
  "embed.p1": "The circle, not the pyramid. The project at the centre, with cross-functional teams around it — decisions are made where the work is done.",
  "embed.p2L": "Planning & takt",
  "embed.p2": "One shared takt for design, production and systematic completion — every trade in the same rhythm.",
  "embed.p3L": "Cost & risk",
  "embed.p3": "The estimate develops with maturity, and risk is steered before it reaches the building — toward a target price you can trust.",
  "embed.popen": "Open the module",
  "embed.whyTitle": "Why the circle beats the pyramid",
  "embed.tradL": "Traditional hierarchy",
  "embed.trad1": "Decisions are made at the top — those who know most are heard last.",
  "embed.trad2": "Each discipline optimises its own silo, not the whole.",
  "embed.trad3": "Information reaches the bottom late — errors surface on site.",
  "embed.trad4": "Long decision paths mean slow response when something changes.",
  "embed.wheelL": "The collaboration wheel",
  "embed.wheel1": "Every team works toward the same goal at the centre.",
  "embed.wheel2": "Cross-functional decisions are made where the work is done.",
  "embed.wheel3": "Premise advisors are pulled in — the right expertise at the right time.",
  "embed.wheel4": "Short distances between disciplines give a fast, shared response.",

  "cost.eyebrow": "Tool 2 · Cost",
  "cost.title": "Cost is developed on<br><span class=\"g\">two principles</span>",
  "cost.lead": "Cost on the project isn't guessed. It's developed, decision by decision, by asking whether each solution does two things:",
  "cost.p1L": "Reduce risk",
  "cost.p1": "Choose solutions that take uncertainty out of the project — what can go wrong always costs the most.",
  "cost.p2L": "Raise maturity",
  "cost.p2": "Lift solutions from sketch to finished, decided basis — maturity is what makes a price something you can trust.",
  "cost.sum": "And the whole thing sums up into one consequence: <b>time</b>. Reduce risk and raise maturity, and the schedule falls into place. Fail to, and you pay for it in time — and time is the most expensive currency on a construction project.",

  "takt.eyebrow": "Tool 3 · Progress",
  "takt.title": "Schedules built as<br><span class=\"g\">production systems</span>",
  "takt.lead": "On both projects the schedule is built as a production system — takt planning and takt control. The work is split into equal-size control areas, and \"trains\" of trades pass through them at a fixed rhythm: concrete, carpentry, plumbing, ventilation, electrical — car after car.",
  "takt.legendArea": "Vertical: control areas (locations and phases)",
  "takt.legendTrain": "Horizontal: time — trades move one location per takt",
  "takt.cars": ["Concrete","Carpentry","Plumbing","Ventilation","Electrical"],
  "takt.locs": ["CA-01 · Foundation","CA-02 · Level 1","CA-03 · Level 2","CA-04 · Level 3","CA-05 · Roof & MEP","CA-06 · Façade"],
  "takt.caption": "A simplified takt: each trade follows the previous one in a fixed rhythm through the control areas. Predictable for everyone — and easy to see when something slips.",
  "takt.note": "On the A-Block, design, the preparatory train and the fit-out train were tied to the same takt, with finished work basis ready six weeks before each control area started.",

  "people.eyebrow": "The most important thing",
  "people.q": "All the methods and all the technology are worth nothing unless you bring the people with you. They are ALWAYS the most important.",
  "people.body": "Both projects put heavy focus on team development and training the people in the project. It is the contact between people that gets projects built — and that makes world-class projects possible. Models and takt and estimates are only tools. The value is in the hands and heads that use them.",

  "tools.eyebrow": "AI tools & our own tools",
  "tools.title": "The tools we <span class=\"g\">showed you</span>",
  "tools.lead": "We demonstrated some of our AI tools, and our own takt tool. Here are the links — do try them yourself.",
  "tools.c1L": "Free digital tools",
  "tools.c1": "Eight small, free tools built on our long experience — each solves one concrete problem in the project day.",
  "tools.c1cta": "See the digital tools",
  "tools.c2L": "Taktplan",
  "tools.c2": "Our own tool for takt planning and control.",
  "tools.c2cta": "Open Taktplan",
  "tools.c3L": "Heard of VDC?",
  "tools.c3": "A short, free introduction to VDC — a good place to start.",
  "tools.c3cta": "Take the course",
  "tools.coursesL": "Training programmes",
  "tools.courses": "Our courses are <b>free</b> and available in <b>Norwegian, English and Spanish</b>. Register and log in (e.g. with Google) and you're ready to go.",
  "tools.coursescta": "See all courses",

  "about.eyebrow": "About us",
  "about.title": "Who you spent the<br>afternoon <span class=\"g\">with</span>",
  "about.lead": "Lean Communications is a small consultancy. We do two things: we develop the skills of people in the construction industry, and we manage complex building projects. Often both at once — because it's in the real projects that competence takes hold.",
  "about.c1L": "Skills development",
  "about.c1": "Courses, training and coaching in Lean and VDC — for the whole organisation, not just management.",
  "about.c2L": "Project management",
  "about.c2": "We step into real, complex building projects and help them implement Lean and VDC in practice.",
  "about.pmNum": "15",
  "about.pmNumL": "project managers, 100% out in real projects",
  "about.pm1": "On top of that, we employ <b>15 project managers</b> who work 100% out in projects — as project managers, design managers, progress planners, project controllers, culture and team developers, and more.",
  "about.pmR1": "Project managers",
  "about.pmR2": "Design managers",
  "about.pmR3": "Progress planners",
  "about.pmR4": "Project controllers",
  "about.pmR5": "Culture &amp; team developers",
  "about.pm2": "Through this contact with real projects we build the experience and competence straight into new training and competence products — so that projects get even better, both in Norway and abroad.",

  "cta.eyebrow": "Thanks for the visit",
  "cta.title": "Best of luck with<br>Digitales Bauen",
  "cta.lead": "It was a pleasure to have you here. Take one thing with you: the tools are the same for everyone — it's the people who make the difference. Keep in touch, and let us know if you're back in Oslo. The beer is ready.",
  "cta.o1L": "The courses",
  "cta.o1": "Free, in three languages. Start with \"Heard of VDC?\".",
  "cta.o1f": "leancommunications.no",
  "cta.o2L": "The tools",
  "cta.o2": "The technology page and Taktplan — try them on your own project.",
  "cta.o2f": "Digital tools",
  "cta.o3L": "Us",
  "cta.o3": "Øyvind and the rest of the Lean Communications crew.",
  "cta.o3f": "Get in touch",

  "footer.tag": "Norway's largest provider of Lean and VDC training for the construction industry. Partners with NTNU. Offices in Oslo and Bergen.",
  "footer.note": "A recap made for MAS Digitales Bauen (FHNW) after VDC Innovation Week in Oslo, June 2026. Project facts from the A-Block K204 (government quarter) and New Bodø Airport. Artwork: AAhkA by Outi Pieski (KORO)."
},

/* ---------------------------------------------------------- ESPAÑOL */
es: {
  "doc.title": "Innovation Week Oslo 2026 — Lean Communications",
  "lang.label": "Idioma",

  "nav.week": "La semana",
  "nav.friday": "Viernes",
  "nav.ablokka": "Bloque A",
  "nav.bodo": "Bodø",
  "nav.method": "El método",
  "nav.tools": "Herramientas",
  "nav.about": "Nosotros",
  "nav.cta": "Sigamos en contacto",

  "hero.eyebrow": "VDC Innovation Week · Oslo · 2–5 junio 2026",
  "hero.langhint": "Este resumen abre en inglés — cambia entre NO / EN / ES / DE arriba a la derecha cuando quieras.",
  "hero.title": "Una semana en cómo<br>Noruega construye — <span class=\"g\">en equipo</span>",
  "hero.sub": "Para los estudiantes del <b>MAS Digitales Bauen</b> de la FHNW — y nuestro buen amigo de Lima. Este es un breve resumen de su semana en Oslo, y en especial de la tarde que pasaron con nosotros el viernes 5 de junio. Gracias por venir.",
  "hero.chipHostL": "Anfitrión",
  "hero.chipHostV": "Øyvind Børstad · Lean Communications",
  "hero.chipWhenL": "Cuándo",
  "hero.chipWhenV": "Viernes 5 de junio, 13:30–15:30",
  "hero.chipWhereL": "Dónde",
  "hero.chipWhereV": "@Nordic Office of Architecture, Oslo",

  "week.eyebrow": "Toda la semana",
  "week.title": "Cuatro días dentro del<br>taller de la <span class=\"g\">construcción</span> noruega",
  "week.lead": "Conocieron toda la cadena — desde los datos digitales de producto y la entrega de información, pasando por grandes consultoras y la co-ubicación, hasta proyectos reales gestionados con Lean y VDC. Justo de lo que trata un máster en Digitales Bauen: unir modelo, datos y personas en algo que de verdad se pueda construir.",
  "week.d1.day": "Martes 2 de junio",
  "week.d1.tag": "Llegada",
  "week.d1.title": "Bienvenidos a Oslo",
  "week.d1.body": "Día de llegada y cena de bienvenida en <b>Frognerseteren</b>, la vieja casa de troncos en el bosque sobre la ciudad — con todo el fiordo de Oslo a sus pies. Un inicio suave antes de una semana intensa.",
  "week.d2.day": "Miércoles 3 de junio",
  "week.d2.tag": "Datos e información",
  "week.d2.title": "Cobuilder · AnkerDB · Conferencia VDC",
  "week.d2.body": "<b>Cobuilder</b> sobre datos de producto en diseño, construcción y operación — el pasaporte digital de producto. <b>AnkerDB</b> sobre la entrega de información en proyectos. La tarde fue para la <b>conferencia VDC</b> en Construction City — networking con la industria noruega.",
  "week.d3.day": "Jueves 4 de junio",
  "week.d3.tag": "Consultoría y co-ubicación",
  "week.d3.title": "Skanska · COWI",
  "week.d3.body": "Visita a la sede de <b>Skanska</b> y a <b>COWI</b> — una consultora internacional en ingeniería, arquitectura, energía y medio ambiente. El tema: co-ubicación y diseño multidisciplinar en la práctica.",
  "week.d4.day": "Viernes 5 de junio",
  "week.d4.tag": "Lean y VDC en la práctica",
  "week.d4.title": "Bane NOR · COWI · Lean Communications",
  "week.d4.body": "Visita a un proyecto de infraestructura con <b>Bane NOR</b> (estación de Kolbotn), co-ubicación en COWI — y al final la tarde con <b>nosotros</b>. Esa es la que hemos recogido aquí.",
  "week.relevance": "Por qué les importa: un máster en Digitales Bauen es el vínculo entre el modelo y la obra. Todo lo que vieron esta semana — datos de producto, entrega de información, co-ubicación, colaboración — es parte del mismo cuadro: convertir información digital en metros cuadrados construidos sin perder a las personas por el camino.",

  "friday.eyebrow": "Viernes · 13:30–15:30",
  "friday.title": "La tarde <span class=\"g\">con nosotros</span>",
  "friday.lead": "Les llevamos por cinco partes. Primero, un poco sobre cómo Noruega trabaja en equipo en los proyectos — antes y ahora. Luego dos proyectos reales, las herramientas que usamos, y lo más importante de todo al final: las personas.",
  "friday.a1": "El Bloque A — una mirada al IPD en Noruega",
  "friday.a2": "Nuevo Aeropuerto de Bodø — contrato colaborativo, herramientas y método en la fase de desarrollo",
  "friday.a3": "Herramientas de IA",
  "friday.a4": "Taller — Innovation Week en Oslo, conclusiones clave",
  "friday.a5": "El Bloque A — visita al proyecto",

  "samspill.eyebrow": "Colaboración en Noruega",
  "samspill.title": "Cómo trabajábamos antes.<br>Cómo trabajamos <span class=\"g\">ahora</span>.",
  "samspill.lead": "Hace veinte años los edificios se dibujaban, se presupuestaban y se licitaban — cada parte optimizando su propia porción. Hoy los mejores proyectos construyen primero el equipo, y el edificio después. Ese es el recorrido que les mostramos.",
  "samspill.thenL": "Hace ~20 años",
  "samspill.then1": "Proceso secuencial: los proyectos se dibujaban, presupuestaban y licitaban paso a paso.",
  "samspill.then2": "Los contratos enfrentaban a las partes — cada una optimizaba su propia parte.",
  "samspill.then3": "Los errores y choques aparecían en obra, donde más cuesta corregirlos.",
  "samspill.then4": "El avance era algo que se reportaba — no algo que se dirigía en tiempo real.",
  "samspill.nowL": "Cómo trabajamos hoy",
  "samspill.now1": "Involucración temprana: cliente, contratista y consultores desarrollan la solución juntos.",
  "samspill.now2": "Contratos colaborativos / IPD con metas, riesgo y beneficio compartidos.",
  "samspill.now3": "Equipos multidisciplinares resolviendo problemas a la vez, en un Big Room, antes de producir.",
  "samspill.now4": "El avance construido como un sistema de producción — takt, planificado y controlado.",
  "samspill.ipdTitle": "El modelo noruego de colaboración — IPD",
  "samspill.ipd0L": "Adquisición",
  "samspill.ipd0": "El cliente elige al contratista y a los consultores para la colaboración — por competencia y actitud, no solo por el precio más bajo.",
  "samspill.ipd1L": "Desarrollo — como un solo equipo",
  "samspill.ipd1": "Cliente, contratista y disciplinas desarrollan la solución juntos, co-ubicados, y acuerdan un precio objetivo antes de empezar a construir.",
  "samspill.ipd1tag": "8–15 meses co-ubicados",
  "samspill.ipd2L": "Ejecución — como un solo equipo",
  "samspill.ipd2": "Se construye sobre el mismo precio objetivo, con riesgo y beneficio compartidos. El bono es zanahoria, no castigo — todos ganan cuando el conjunto tiene éxito.",
  "samspill.ipd2tag": "Riesgo y beneficio compartidos",
  "samspill.ipdQuote": "La colaboración se diseña — no se deja al azar.",

  "ablokka.eyebrow": "Proyecto 1 · El Bloque A, nuevo barrio gubernamental",
  "ablokka.title": "Un edificio donde calidad, costo<br>y tiempo se <span class=\"g\">desarrollaron</span>, no se adivinaron",
  "ablokka.lead": "El Bloque A (K204) del nuevo barrio gubernamental de Oslo es un proyecto IPD donde el contratista HENT, el cliente Statsbygg y las disciplinas desarrollaron la solución juntos. Contamos la historia de cómo se dirigió con un foco implacable en calidad, costo y tiempo — y cómo el contrato lo hizo posible.",
  "ablokka.s1v": "3,2 mil mill",
  "ablokka.s1t": "precio objetivo (NOK) para K204 — la estimación se desarrolló como cifra viva hacia él",
  "ablokka.s2v": "20+",
  "ablokka.s2t": "áreas de control en producción a la vez, gestionadas con planificación takt",
  "ablokka.s3v": "Oct 2025",
  "ablokka.s3t": "el edificio proyectado se entregó en octubre de 2025 — un mes antes de lo previsto; mudanza desde enero de 2026",
  "ablokka.bigroomCap": "Del tablero digital Big Room del Bloque A K204: planes de avance, organigramas operativo y contractual, evaluación de madurez, fiabilidad del plan y la estimación dinámica — todo en un lugar, todo vivo.",
  "ablokka.photo1": "Suelta tu propia foto del Bloque A / barrio gubernamental",
  "ablokka.photo2": "Suelta una foto de la visita al proyecto",
  "ablokka.illTitle": "Tres cosas que mostramos del Bloque A",
  "ablokka.ill1L": "Modelo de organización",
  "ablokka.ill1cap": "Un modelo circular con equipos scrum multidisciplinares alrededor del proyecto en el centro — no una pirámide, sino una rueda.",
  "ablokka.illOrgCenter": "El proyecto",
  "ablokka.illOrgK1": "Liderazgo colaborativo",
  "ablokka.illOrgK2": "Equipos de disciplina",
  "ablokka.illOrgK3": "Equipos de proceso",
  "ablokka.ill2L": "Costo &amp; madurez",
  "ablokka.ill2cap": "El costo se desarrolla hacia el precio objetivo mientras sube la madurez de las soluciones — dos curvas que se encuentran.",
  "ablokka.illCalcK1": "Estimación",
  "ablokka.illCalcK2": "Precio objetivo",
  "ablokka.illCalcK3": "Madurez",
  "ablokka.ill3L": "Plan takt",
  "ablokka.ill3cap": "Un takt común para diseño, producción y finalización sistemática — oficio tras oficio por cada área de control.",
  "ablokka.illTaktP1": "Diseño",
  "ablokka.illTaktP2": "Producción",
  "ablokka.illTaktP3": "Finalización",
  "ablokka.shotCap": "El Bloque A en el nuevo barrio gubernamental de Oslo, al anochecer.",
  "ablokka.resEyebrow": "Producción fase 2 · resultados en la entrega",
  "ablokka.resLead": "El enfoque integrado no solo mejoró la colaboración — produjo resultados medibles y excepcionales en todas las dimensiones.",
  "ablokka.res1V": "100%",
  "ablokka.res1L": "Hitos entregados",
  "ablokka.res1S": "Todos y cada uno de los hitos cumplidos",
  "ablokka.res2V": "1 mes",
  "ablokka.res2L": "Antes de plazo",
  "ablokka.res2S": "Terminado antes",
  "ablokka.res3V": "3%",
  "ablokka.res3L": "Bajo presupuesto",
  "ablokka.res3S": "Control de costos disciplinado",
  "ablokka.res4V": "14",
  "ablokka.res4L": "Órdenes de cambio",
  "ablokka.res4S": "Todas acordadas antes de la entrega",
  "ablokka.resQuote": "La previsibilidad se diseña — no se espera.",

  "aahka.eyebrow": "El Bloque A · La pared inclinada",
  "aahka.title": "AAhkA — toda Noruega<br>reunida en <span class=\"g\">una obra</span>",
  "aahka.lead": "Justo dentro de la entrada principal del Bloque A está la Sala Pirámide. La gran pared inclinada casi pedía una obra de arte — y la tuvo. <b>AAhkA</b>, de la artista sami-finlandesa <b>Outi Pieski</b>, mide más de 51 metros de alto y cubre más de 700 metros cuadrados. Para muchos será el primer encuentro con el nuevo barrio gubernamental.",
  "aahka.b1": "La obra es parte integrada de la superficie triangular e inclinada de la pared, construida con listones de abedul unidos en distintas direcciones — algunos en madera natural, otros pintados, dorados o tallados con ornamentos. Surge como un relieve dentro de la propia topografía del muro.",
  "aahka.b2": "AAhkA muestra a una mujer de medio perfil con el gorro sami de cuernos <i>ládjogahpir</i>, anillos de latón en los dedos y un bastón con motivos — todo ligado al <i>duodji</i>, la artesanía sami, donde el proceso importa tanto como la obra terminada.",
  "aahka.b3": "El título alude a la Madre Tierra como persona jurídica — protectora de la naturaleza, un recordatorio de que el ser humano y la naturaleza están en una relación de igualdad. La fachada de vidrio hace que la obra se vea también desde fuera, como parte del paisaje urbano.",
  "aahka.tieIn": "Por qué les trajimos aquí: una obra de 700 m², integrada en una pared inclinada, montada en tres meses en mitad de una obra estrictamente controlada por takt — eso es colaboración entre arquitecto, artista y contratista en su forma más pura. \"No es habitual que un contratista ayude a construir una obra de arte\", dijo HENT.",
  "aahka.fact1L": "Altura",
  "aahka.fact1V": "51 m",
  "aahka.fact2L": "Superficie",
  "aahka.fact2V": "700+ m²",
  "aahka.fact3L": "Montaje",
  "aahka.fact3V": "3 meses",
  "aahka.fact4L": "Artista",
  "aahka.fact4V": "Outi Pieski",
  "aahka.photo": "Suelta tu foto de AAhkA en la Sala Pirámide",
  "aahka.src": "Fuentes: KORO (Arte Público de Noruega), Store norske leksikon, Arkitektur.no. AAhkA se inauguró en otoño de 2025.",

  "bodo.eyebrow": "Proyecto 2 · Nuevo Aeropuerto de Bodø",
  "bodo.title": "La misma lógica,<br>a la escala de un <span class=\"g\">aeropuerto</span>",
  "bodo.lead": "Luego saltamos a Bodø. El nuevo aeropuerto se traslada ~900 metros, libera todo un barrio nuevo, y se construye como contrato colaborativo entre Avinor y los contratistas. Mucho se hace como en el Bloque A — pero aquí entramos más a fondo en la caja de herramientas de la fase de desarrollo.",
  "bodo.s1v": "2,4 mil mill",
  "bodo.s1t": "precio objetivo (sin IVA) para la nueva terminal y edificios operativos — contrato colaborativo con Avinor",
  "bodo.s2v": "~27 000 m²",
  "bodo.s2t": "terminal y edificios operativos (HENT) en un contrato llave en mano con colaboración",
  "bodo.s3v": "2029/30",
  "bodo.s3t": "apertura prevista; fase de desarrollo y precio objetivo antes de la primera excavación",
  "bodo.heroCap": "Nuevo Aeropuerto de Bodø — render, Team NLBO.",
  "bodo.tpTitle": "Cómo se define el precio objetivo — y qué pasa por encima o por debajo",
  "bodo.tpAxisY": "Costo",
  "bodo.tpAxisX": "Tiempo →",
  "bodo.tpDev": "Fase de desarrollo",
  "bodo.tpFinal": "Costo final",
  "bodo.tpSeg1": "Costo neto",
  "bodo.tpSeg2": "Riesgo y oportunidad",
  "bodo.tpSeg3": "Gastos generales y beneficio",
  "bodo.tpB3L": "Precio objetivo",
  "bodo.tpCap": "Tope",
  "bodo.tpFloor": "Piso",
  "bodo.tpZoneRisk": "Riesgo compartido",
  "bodo.tpZoneOpp": "Oportunidad compartida",
  "bodo.tpSave": "Ahorro",
  "bodo.tpBuildNote": "Las tres partes son visibles para las partes. A medida que maduran las soluciones, baja la incertidumbre — y el precio objetivo se vuelve una cifra confiable.",
  "bodo.goalsTitle": "NLBO — objetivos al momento de la entrega",
  "bodo.gSHA": "SST",
  "bodo.gSHA1": "Cero lesiones",
  "bodo.gCost": "Costo",
  "bodo.gCost1": "NOK 2,4 mil mill sin IVA",
  "bodo.gCost2": "«Superar» el precio objetivo",
  "bodo.gQual": "Calidad",
  "bodo.gQual1": "Sin defectos significativos en la entrega",
  "bodo.gTime": "Tiempo",
  "bodo.gTime1": "ICT completo: 01.05.28",
  "bodo.gTime2": "MC: 01.12.27",
  "bodo.gTime3": "Entrega: 01.06.28",
  "bodo.samspillNote": "Colaboración (samspill) significa que cliente y contratista pasan primero juntos por una <b>fase de desarrollo</b> — optimizando soluciones, cuantificando la incertidumbre y acordando un <b>precio objetivo</b> — antes de empezar a construir. Ahí se toman las grandes decisiones.",

  "org.eyebrow": "Herramienta 1 · Organización",
  "org.title": "El modelo <span class=\"g\">circular</span>",
  "org.lead": "Detallamos el plan de organización: equipos scrum multidisciplinares alrededor de un centro común, todos con la misma tarea — optimizar el proyecto en su conjunto. Sin pirámide. Un círculo, donde las disciplinas se encuentran en el centro.",
  "org.hub": "Equipos<br>colaborativos",
  "org.t1": "Estructura",
  "org.t2": "Fachada y techo",
  "org.t3": "Acabados",
  "org.t4": "Instalaciones",
  "org.t5": "Diseño",
  "org.t6": "Compras",
  "org.t7": "Producción",
  "org.t8": "BIM / VDC",
  "org.caption": "Pasa el cursor sobre un equipo para verlo destacarse. Cada equipo es dueño de su parte, pero trabaja hacia el mismo centro.",
  "embed.kicker": "Pruébalo",
  "embed.title": "El núcleo del motor VDC",
  "embed.lead": "Tres cosas forman el núcleo del motor VDC. Recorre cada una en el modelo interactivo de abajo — o ábrelo en pantalla completa.",
  "embed.open": "Abrir en pantalla completa",
  "embed.close": "Cerrar",
  "embed.p1L": "Organización",
  "embed.p1": "El círculo, no la pirámide. El proyecto en el centro, con equipos multidisciplinares alrededor — las decisiones se toman donde se hace el trabajo.",
  "embed.p2L": "Planes & takt",
  "embed.p2": "Un takt común para diseño, producción y finalización sistemática — cada oficio en el mismo ritmo.",
  "embed.p3L": "Costo & riesgo",
  "embed.p3": "La estimación se desarrolla según la madurez, y el riesgo se gestiona antes de que llegue al edificio — hacia un precio objetivo confiable.",
  "embed.popen": "Abrir el módulo",
  "embed.whyTitle": "Por qué el círculo gana a la pirámide",
  "embed.tradL": "Jerarquía tradicional",
  "embed.trad1": "Las decisiones se toman arriba — quienes más saben se escuchan al final.",
  "embed.trad2": "Cada disciplina optimiza su propio silo, no el conjunto.",
  "embed.trad3": "La información llega abajo tarde — los errores aparecen en obra.",
  "embed.trad4": "Las largas vías de decisión dan una respuesta lenta ante los cambios.",
  "embed.wheelL": "La rueda de colaboración",
  "embed.wheel1": "Todos los equipos trabajan hacia el mismo objetivo en el centro.",
  "embed.wheel2": "Las decisiones multidisciplinares se toman donde se hace el trabajo.",
  "embed.wheel3": "Los asesores de premisas entran por pull — la competencia justa en el momento justo.",
  "embed.wheel4": "Las distancias cortas entre disciplinas dan una respuesta rápida y común.",

  "cost.eyebrow": "Herramienta 2 · Costo",
  "cost.title": "El costo se desarrolla sobre<br><span class=\"g\">dos principios</span>",
  "cost.lead": "El costo del proyecto no se adivina. Se desarrolla, decisión a decisión, preguntando si cada solución hace dos cosas:",
  "cost.p1L": "Reducir el riesgo",
  "cost.p1": "Elige soluciones que saquen la incertidumbre del proyecto — lo que puede salir mal siempre es lo que más cuesta.",
  "cost.p2L": "Aumentar la madurez",
  "cost.p2": "Lleva las soluciones del boceto a una base terminada y decidida — la madurez es lo que hace que un precio sea confiable.",
  "cost.sum": "Y todo se resume en una sola consecuencia: el <b>tiempo</b>. Si reduces el riesgo y aumentas la madurez, el avance encaja. Si no lo logras, lo pagas en tiempo — y el tiempo es la moneda más cara de una obra.",

  "takt.eyebrow": "Herramienta 3 · Avance",
  "takt.title": "Planes de avance construidos como<br><span class=\"g\">sistemas de producción</span>",
  "takt.lead": "En ambos proyectos el avance se construye como un sistema de producción — planificación y control takt. El trabajo se divide en áreas de control del mismo tamaño, y \"trenes\" de oficios pasan por ellas a un ritmo fijo: hormigón, carpintería, fontanería, ventilación, electricidad — vagón tras vagón.",
  "takt.legendArea": "Vertical: áreas de control (ubicaciones y fases)",
  "takt.legendTrain": "Horizontal: tiempo — los oficios avanzan una ubicación por takt",
  "takt.cars": ["Hormigón","Carpintería","Fontanería","Ventilación","Electricidad"],
  "takt.locs": ["AC-01 · Cimentación","AC-02 · Planta 1","AC-03 · Planta 2","AC-04 · Planta 3","AC-05 · Cubierta y MEP","AC-06 · Fachada"],
  "takt.caption": "Un takt simplificado: cada oficio sigue al anterior a un ritmo fijo por las áreas de control. Predecible para todos — y fácil de ver cuando algo se atrasa.",
  "takt.note": "En el Bloque A, el diseño, el tren preparatorio y el tren de acabados se ataron al mismo takt, con la base de trabajo lista seis semanas antes de iniciar cada área de control.",

  "people.eyebrow": "Lo más importante",
  "people.q": "Todos los métodos y toda la tecnología no valen nada si no llevas contigo a las personas. Ellas son SIEMPRE lo más importante.",
  "people.body": "Ambos proyectos pusieron un fuerte foco en el desarrollo del equipo y en entrenar a las personas del proyecto. Es el contacto entre personas lo que hace que los proyectos se construyan — y lo que hace posibles los proyectos de clase mundial. Los modelos, el takt y las estimaciones son solo herramientas. El valor está en las manos y las cabezas que las usan.",

  "tools.eyebrow": "Herramientas de IA y propias",
  "tools.title": "Las herramientas que les <span class=\"g\">mostramos</span>",
  "tools.lead": "Mostramos algunas de nuestras herramientas de IA, y nuestra propia herramienta takt. Aquí están los enlaces — pruébenlas ustedes mismos.",
  "tools.c1L": "Herramientas digitales gratuitas",
  "tools.c1": "Ocho herramientas pequeñas y gratuitas basadas en nuestra larga experiencia — cada una resuelve un problema concreto del día a día.",
  "tools.c1cta": "Ver las herramientas digitales",
  "tools.c2L": "Taktplan",
  "tools.c2": "Nuestra propia herramienta de planificación y control takt.",
  "tools.c2cta": "Abrir Taktplan",
  "tools.c3L": "¿Has oído de VDC?",
  "tools.c3": "Una introducción corta y gratuita al VDC — un buen punto de partida.",
  "tools.c3cta": "Hacer el curso",
  "tools.coursesL": "Programas de formación",
  "tools.courses": "Nuestros cursos son <b>gratuitos</b> y están en <b>noruego, inglés y español</b>. Regístrate e inicia sesión (por ejemplo con Google) y ya puedes empezar.",
  "tools.coursescta": "Ver todos los cursos",

  "about.eyebrow": "Sobre nosotros",
  "about.title": "Con quién pasaron<br>la <span class=\"g\">tarde</span>",
  "about.lead": "Lean Communications es una pequeña consultora. Hacemos dos cosas: desarrollamos las competencias de las personas del sector de la construcción, y dirigimos proyectos de construcción complejos. A menudo ambas a la vez — porque es en los proyectos reales donde la competencia se afianza.",
  "about.c1L": "Desarrollo de competencias",
  "about.c1": "Cursos, formación y entrenamiento en Lean y VDC — para toda la organización, no solo la dirección.",
  "about.c2L": "Dirección de proyectos",
  "about.c2": "Entramos en proyectos de construcción reales y complejos y les ayudamos a implementar Lean y VDC en la práctica.",
  "about.pmNum": "15",
  "about.pmNumL": "jefes de proyecto, 100% en proyectos reales",
  "about.pm1": "Además, tenemos <b>15 jefes de proyecto</b> que trabajan al 100% en proyectos — como jefes de proyecto, jefes de diseño, planificadores de avance, controladores de proyecto, desarrolladores de cultura y equipo, y más.",
  "about.pmR1": "Jefes de proyecto",
  "about.pmR2": "Jefes de diseño",
  "about.pmR3": "Planificadores de avance",
  "about.pmR4": "Controladores de proyecto",
  "about.pmR5": "Desarrolladores de cultura y equipo",
  "about.pm2": "A través de este contacto con proyectos reales construimos la experiencia y la competencia directamente en nuevos productos de formación y competencia — para que los proyectos sean aún mejores, tanto en Noruega como en el extranjero.",

  "cta.eyebrow": "Gracias por la visita",
  "cta.title": "Mucha suerte con<br>Digitales Bauen",
  "cta.lead": "Fue un placer tenerles aquí. Llévense una sola cosa: las herramientas son iguales para todos — son las personas las que marcan la diferencia. Sigamos en contacto, y avisen si vuelven a Oslo. La cerveza está lista.",
  "cta.o1L": "Los cursos",
  "cta.o1": "Gratis, en tres idiomas. Empiecen con \"¿Has oído de VDC?\".",
  "cta.o1f": "leancommunications.no",
  "cta.o2L": "Las herramientas",
  "cta.o2": "La página de tecnología y Taktplan — pruébenlas en su propio proyecto.",
  "cta.o2f": "Herramientas digitales",
  "cta.o3L": "Nosotros",
  "cta.o3": "Øyvind y el resto del equipo de Lean Communications.",
  "cta.o3f": "Contáctanos",

  "footer.tag": "El mayor proveedor de formación en Lean y VDC para la construcción en Noruega. Colabora con la NTNU. Oficinas en Oslo y Bergen.",
  "footer.note": "Un resumen hecho para MAS Digitales Bauen (FHNW) tras la VDC Innovation Week en Oslo, junio de 2026. Datos de proyecto del Bloque A K204 (barrio gubernamental) y el Nuevo Aeropuerto de Bodø. Obra de arte: AAhkA de Outi Pieski (KORO)."
},

/* ---------------------------------------------------------- DEUTSCH (CH) */
de: {
  "doc.title": "Innovation Week Oslo 2026 — Lean Communications",
  "lang.label": "Sprache",

  "nav.week": "Die Woche",
  "nav.friday": "Freitag",
  "nav.ablokka": "A-Block",
  "nav.bodo": "Bodø",
  "nav.method": "Die Methode",
  "nav.tools": "Werkzeuge",
  "nav.about": "Über uns",
  "nav.cta": "In Kontakt bleiben",

  "hero.eyebrow": "VDC Innovation Week · Oslo · 2.–5. Juni 2026",
  "hero.langhint": "Diese Zusammenfassung öffnet auf Englisch — wechsle oben rechts jederzeit zwischen NO / EN / ES / DE.",
  "hero.title": "Eine Woche, wie<br>Norwegen baut — <span class=\"g\">gemeinsam</span>",
  "hero.sub": "Für die Studierenden des <b>MAS Digitales Bauen</b> an der FHNW — und unseren guten Freund aus Lima. Dies ist eine kurze Zusammenfassung eurer Woche in Oslo, und besonders des Nachmittags, den ihr am Freitag, 5. Juni, mit uns verbracht habt. Danke für euren Besuch.",
  "hero.chipHostL": "Gastgeber",
  "hero.chipHostV": "Øyvind Børstad · Lean Communications",
  "hero.chipWhenL": "Wann",
  "hero.chipWhenV": "Freitag 5. Juni, 13:30–15:30",
  "hero.chipWhereL": "Wo",
  "hero.chipWhereV": "@Nordic Office of Architecture, Oslo",

  "week.eyebrow": "Die ganze Woche",
  "week.title": "Vier Tage in der<br>Werkstatt des norwegischen <span class=\"g\">Bauens</span>",
  "week.lead": "Ihr habt die ganze Kette getroffen — von digitalen Produktdaten und Informationslieferungen über grosse Ingenieurbüros und Co-Location bis zu echten Projekten, die mit Lean und VDC gesteuert werden. Genau darum geht es bei einem Master in Digitalem Bauen: Modell, Daten und Menschen zu etwas zu verbinden, das sich tatsächlich bauen lässt.",
  "week.d1.day": "Dienstag 2. Juni",
  "week.d1.tag": "Ankunft",
  "week.d1.title": "Willkommen in Oslo",
  "week.d1.body": "Anreisetag und ein Willkommensessen im <b>Frognerseteren</b>, der alten Holzlodge im Wald hoch über der Stadt — mit dem ganzen Oslofjord zu Füssen. Ein sanfter Auftakt vor einer dichten Woche.",
  "week.d2.day": "Mittwoch 3. Juni",
  "week.d2.tag": "Daten & Information",
  "week.d2.title": "Cobuilder · AnkerDB · VDC-Konferenz",
  "week.d2.body": "<b>Cobuilder</b> über Produktdaten durch Planung, Bau und Betrieb — der digitale Produktpass. <b>AnkerDB</b> über Informationslieferungen in Bauprojekten. Der Abend galt der <b>VDC-Konferenz</b> in der Construction City — Networking mit der norwegischen Branche.",
  "week.d3.day": "Donnerstag 4. Juni",
  "week.d3.tag": "Beratung & Co-Location",
  "week.d3.title": "Skanska · COWI",
  "week.d3.body": "Ein Besuch im Hauptsitz von <b>Skanska</b> und bei <b>COWI</b> — einem internationalen Beratungsunternehmen für Ingenieurwesen, Architektur, Energie und Umwelt. Das Thema: Co-Location und interdisziplinäre Planung in der Praxis.",
  "week.d4.day": "Freitag 5. Juni",
  "week.d4.tag": "Lean & VDC in der Praxis",
  "week.d4.title": "Bane NOR · COWI · Lean Communications",
  "week.d4.body": "Ein Besuch eines Infrastrukturprojekts mit <b>Bane NOR</b> (Bahnhof Kolbotn), Co-Location bei COWI — und schliesslich der Nachmittag mit <b>uns</b>. Den haben wir hier festgehalten.",
  "week.relevance": "Warum das für euch zählt: Ein Master in Digitalem Bauen ist das Bindeglied zwischen dem Modell und der schlammigen Baustelle. Alles, was ihr diese Woche gesehen habt — Produktdaten, Informationslieferung, Co-Location, Zusammenarbeit — gehört zum selben Bild: digitale Informationen in gebaute Quadratmeter zu verwandeln, ohne die Menschen unterwegs zu verlieren.",

  "friday.eyebrow": "Freitag · 13:30–15:30",
  "friday.title": "Der Nachmittag <span class=\"g\">mit uns</span>",
  "friday.lead": "Wir haben euch durch fünf Teile geführt. Zuerst ein wenig dazu, wie Norwegen bei Bauprojekten zusammenarbeitet — damals und heute. Dann zwei echte Projekte, die Werkzeuge, die wir nutzen, und zum Schluss das Wichtigste von allem: die Menschen.",
  "friday.a1": "Der A-Block — Einblick in IPD in Norwegen",
  "friday.a2": "Neuer Flughafen Bodø — Partnervertrag, Werkzeuge und Methoden in der Entwicklungsphase",
  "friday.a3": "KI-Werkzeuge",
  "friday.a4": "Workshop — Innovation Week in Oslo, wichtigste Erkenntnisse",
  "friday.a5": "Der A-Block — Projektbesuch",

  "samspill.eyebrow": "Zusammenarbeit in Norwegen",
  "samspill.title": "Wie wir damals arbeiteten.<br>Wie wir <span class=\"g\">heute</span> arbeiten.",
  "samspill.lead": "Vor zwanzig Jahren wurden Gebäude meist gezeichnet, kalkuliert und ausgeschrieben — jede Partei optimierte ihr eigenes Stück. Heute bauen die besten Projekte zuerst das Team und danach das Gebäude. Diesen Weg haben wir euch gezeigt.",
  "samspill.thenL": "vor ~20 Jahren",
  "samspill.then1": "Sequenzieller Prozess: Projekte wurden Schritt für Schritt gezeichnet, kalkuliert und ausgeschrieben.",
  "samspill.then2": "Verträge stellten die Parteien gegeneinander — jede optimierte ihren eigenen Teil.",
  "samspill.then3": "Fehler und Kollisionen zeigten sich auf der Baustelle, wo ihre Behebung am teuersten ist.",
  "samspill.then4": "Fortschritt war etwas, worüber man berichtete — nicht etwas, das man in Echtzeit steuerte.",
  "samspill.nowL": "Wie wir heute arbeiten",
  "samspill.now1": "Frühe Einbindung: Bauherr, Unternehmer und Berater entwickeln die Lösung gemeinsam.",
  "samspill.now2": "Partnerschaftliche / IPD-Verträge mit gemeinsamen Zielen, geteiltem Risiko und geteiltem Gewinn.",
  "samspill.now3": "Interdisziplinäre Teams, die Probleme gleichzeitig lösen, im Big Room, vor der Produktion.",
  "samspill.now4": "Fortschritt als Produktionssystem aufgebaut — Takt, geplant und kontrolliert.",
  "samspill.ipdTitle": "Das norwegische Kooperationsmodell — IPD",
  "samspill.ipd0L": "Beschaffung",
  "samspill.ipd0": "Der Bauherr wählt Unternehmer und Berater für die Zusammenarbeit aus — nach Kompetenz und Haltung, nicht allein nach dem tiefsten Preis.",
  "samspill.ipd1L": "Entwicklung — als ein Team",
  "samspill.ipd1": "Bauherr, Unternehmer und Fachdisziplinen entwickeln die Lösung gemeinsam, am selben Ort, und vereinbaren einen Zielpreis, bevor der Bau beginnt.",
  "samspill.ipd1tag": "8–15 Monate am selben Ort",
  "samspill.ipd2L": "Ausführung — als ein Team",
  "samspill.ipd2": "Aufbauend auf demselben Zielpreis, mit geteiltem Risiko und geteiltem Gewinn. Der Bonus ist ein Anreiz, kein Druckmittel — alle gewinnen, wenn das Ganze gelingt.",
  "samspill.ipd2tag": "Geteiltes Risiko & geteilter Gewinn",
  "samspill.ipdQuote": "Zusammenarbeit wird gestaltet — sie wird nicht dem Zufall überlassen.",

  "ablokka.eyebrow": "Projekt 1 · Der A-Block, neues Regierungsviertel",
  "ablokka.title": "Ein Gebäude, in dem Qualität, Kosten<br>und Zeit <span class=\"g\">entwickelt</span> statt geschätzt wurden",
  "ablokka.lead": "Der A-Block (K204) im neuen Regierungsviertel von Oslo ist ein IPD-Projekt, bei dem der Unternehmer HENT, der Bauherr Statsbygg und die Fachdisziplinen die Lösung gemeinsam entwickelten. Wir erzählten, wie das Projekt mit unermüdlichem Fokus auf Qualität, Kosten und Zeit geführt wurde — und wie der Vertrag das möglich machte.",
  "ablokka.s1v": "3,2 Mrd.",
  "ablokka.s1t": "Zielpreis (NOK) für K204 — die Kalkulation wurde als lebende Zahl darauf hin entwickelt",
  "ablokka.s2v": "20+",
  "ablokka.s2t": "Kontrollbereiche gleichzeitig in Produktion, mit Taktplanung gesteuert",
  "ablokka.s3v": "Okt. 2025",
  "ablokka.s3t": "das geplante Gebäude wurde im Oktober 2025 übergeben — einen Monat vor Plan; Bezug ab Januar 2026",
  "ablokka.bigroomCap": "Vom digitalen Big-Room-Board des A-Blocks K204: Fortschrittspläne, operative und vertragliche Organigramme, Reifegradbewertung, Planzuverlässigkeit und die dynamische Kalkulation — alles an einem Ort, alles lebendig.",
  "ablokka.photo1": "Lege hier dein eigenes Foto vom A-Block / Regierungsviertel ab",
  "ablokka.photo2": "Lege hier ein Foto vom Projektbesuch ab",
  "ablokka.illTitle": "Drei Dinge, die wir vom A-Block gezeigt haben",
  "ablokka.ill1L": "Organisationsmodell",
  "ablokka.ill1cap": "Ein kreisförmiges Modell mit interdisziplinären Scrum-Teams rund um das Projekt im Zentrum — keine Hierarchie, sondern ein Rad.",
  "ablokka.illOrgCenter": "Das Projekt",
  "ablokka.illOrgK1": "Kooperationsleitung",
  "ablokka.illOrgK2": "Fachteams",
  "ablokka.illOrgK3": "Prozessteams",
  "ablokka.ill2L": "Kosten &amp; Reifegrad",
  "ablokka.ill2cap": "Die Kosten werden zum Zielpreis hin entwickelt, während der Reifegrad der Lösungen steigt — zwei Kurven, die sich treffen.",
  "ablokka.illCalcK1": "Kalkulation",
  "ablokka.illCalcK2": "Zielpreis",
  "ablokka.illCalcK3": "Reifegrad",
  "ablokka.ill3L": "Taktplan",
  "ablokka.ill3cap": "Ein gemeinsamer Takt für Planung, Produktion und systematische Fertigstellung — Gewerk für Gewerk durch jeden Kontrollbereich.",
  "ablokka.illTaktP1": "Planung",
  "ablokka.illTaktP2": "Produktion",
  "ablokka.illTaktP3": "Fertigstellung",
  "ablokka.shotCap": "Der A-Block im neuen Regierungsviertel von Oslo, in der Dämmerung.",
  "ablokka.resEyebrow": "Produktion Phase 2 · Ergebnisse bei der Übergabe",
  "ablokka.resLead": "Der integrierte Ansatz hat nicht nur die Zusammenarbeit verbessert — er brachte messbare, aussergewöhnliche Ergebnisse in jeder Dimension.",
  "ablokka.res1V": "100%",
  "ablokka.res1L": "Meilensteine geliefert",
  "ablokka.res1S": "Jeder einzelne Meilenstein erreicht",
  "ablokka.res2V": "1 Mt.",
  "ablokka.res2L": "Vor dem Zeitplan",
  "ablokka.res2S": "Früher fertiggestellt",
  "ablokka.res3V": "3%",
  "ablokka.res3L": "Unter Budget",
  "ablokka.res3S": "Disziplinierte Kostenkontrolle",
  "ablokka.res4V": "14",
  "ablokka.res4L": "Nachträge",
  "ablokka.res4S": "Alle vor der Übergabe vereinbart",
  "ablokka.resQuote": "Vorhersehbarkeit wird gestaltet — nicht erhofft.",

  "aahka.eyebrow": "Der A-Block · Die schräge Wand",
  "aahka.title": "AAhkA — ganz Norwegen<br>in <span class=\"g\">einem Kunstwerk</span> vereint",
  "aahka.lead": "Gleich hinter dem Haupteingang des A-Blocks liegt der Pyramidenraum. Die grosse, schräge Wand verlangte geradezu nach einem Kunstwerk — und bekam eines. <b>AAhkA</b> der samisch-finnischen Künstlerin <b>Outi Pieski</b> ist über 51 Meter hoch und bedeckt mehr als 700 Quadratmeter. Für viele wird es die allererste Begegnung mit dem neuen Regierungsviertel sein.",
  "aahka.b1": "Das Werk ist integraler Teil der dreieckigen, schrägen Wandfläche, aufgebaut aus zusammengefügten Birkenleisten in verschiedenen Richtungen — manche blank belassen, andere bemalt, vergoldet oder mit Ornamenten geschnitzt. Es entsteht als Relief in der eigenen Topografie der Wand.",
  "aahka.b2": "AAhkA zeigt eine Frau im Halbprofil mit der samischen Hörnermütze <i>ládjogahpir</i>, Messingringen an den Fingern und einem gemusterten Wanderstab — alles verbunden mit <i>duodji</i>, dem samischen Handwerk, bei dem der Prozess ebenso zählt wie das fertige Werk.",
  "aahka.b3": "Der Titel verweist auf Mutter Erde als juristische Person — eine Beschützerin der Natur, eine Erinnerung daran, dass Mensch und Natur in einem gleichwertigen Verhältnis stehen. Durch die Glasfassade der Wand ist das Werk auch von aussen sichtbar, als Teil des Stadtbilds.",
  "aahka.tieIn": "Warum wir euch hierher gebracht haben: ein 700 m² grosses Kunstwerk, in eine schräge Wand integriert, in drei Monaten mitten in einem eng taktgesteuerten Bau montiert — das ist Zusammenarbeit zwischen Architekt, Künstlerin und Unternehmer in Reinform. «Es kommt nicht oft vor, dass ein Unternehmer beim Bau eines Kunstwerks mithelfen darf», wie HENT es ausdrückte.",
  "aahka.fact1L": "Höhe",
  "aahka.fact1V": "51 m",
  "aahka.fact2L": "Fläche",
  "aahka.fact2V": "700+ m²",
  "aahka.fact3L": "Montage",
  "aahka.fact3V": "3 Monate",
  "aahka.fact4L": "Künstlerin",
  "aahka.fact4V": "Outi Pieski",
  "aahka.photo": "Lege hier dein Foto von AAhkA im Pyramidenraum ab",
  "aahka.src": "Quellen: KORO (Öffentliche Kunst Norwegen), Store norske leksikon, Arkitektur.no. AAhkA wurde im Herbst 2025 enthüllt.",

  "bodo.eyebrow": "Projekt 2 · Neuer Flughafen Bodø",
  "bodo.title": "Dasselbe Denken,<br>hochskaliert auf einen ganzen <span class=\"g\">Flughafen</span>",
  "bodo.lead": "Dann sprangen wir nach Bodø. Der neue Flughafen wird ~900 Meter verschoben, wodurch ein ganz neues Stadtviertel frei wird, und als Partnervertrag zwischen Avinor und den Unternehmern gebaut. Vieles läuft wie beim A-Block — aber hier sind wir tiefer in den eigentlichen Werkzeugkasten der Entwicklungsphase eingestiegen.",
  "bodo.s1v": "2,4 Mrd.",
  "bodo.s1t": "Zielpreis (NOK exkl. MwSt.) für das neue Terminal und die Betriebsgebäude — Partnervertrag mit Avinor",
  "bodo.s2v": "~27 000 m²",
  "bodo.s2t": "Terminal und Betriebsgebäude (HENT) als Totalunternehmer mit Zusammenarbeit",
  "bodo.s3v": "2029/30",
  "bodo.s3t": "geplante Eröffnung; Entwicklungsphase und Zielpreis vor dem ersten Spatenstich",
  "bodo.heroCap": "Neuer Flughafen Bodø — Visualisierung, Team NLBO.",
  "bodo.tpTitle": "Wie der Zielpreis definiert wird — und was über oder unter ihm geschieht",
  "bodo.tpSeg1": "Selbstkosten",
  "bodo.tpSeg2": "Risiko & Chancen",
  "bodo.tpSeg3": "Zuschlag & Gewinn",
  "bodo.tpBuildNote": "Alle drei Teile sind für die Parteien sichtbar. Mit der Reife der Lösungen sinkt die Unsicherheit — und der Zielpreis wird zu einer Zahl, der man vertrauen kann.",
  "bodo.tpB3L": "Zielpreis",
  "bodo.tpAxisY": "Kosten",
  "bodo.tpAxisX": "Zeit →",
  "bodo.tpDev": "Entwicklungsphase",
  "bodo.tpFinal": "Endkosten",
  "bodo.tpCap": "Deckel",
  "bodo.tpFloor": "Boden",
  "bodo.tpZoneRisk": "Risiko geteilt",
  "bodo.tpZoneOpp": "Chancen geteilt",
  "bodo.tpSave": "Einsparung",
  "bodo.goalsTitle": "NLBO — Ergebnisziele bei der Übergabe",
  "bodo.gSHA": "HSE",
  "bodo.gSHA1": "Null Verletzungen",
  "bodo.gCost": "Kosten",
  "bodo.gCost1": "NOK 2,4 Mrd. exkl. MwSt.",
  "bodo.gCost2": "Den Zielpreis «schlagen»",
  "bodo.gQual": "Qualität",
  "bodo.gQual1": "Keine wesentlichen Mängel bei der Übergabe",
  "bodo.gTime": "Zeit",
  "bodo.gTime1": "Inbetriebnahme: 01.05.28",
  "bodo.gTime2": "MC: 01.12.27",
  "bodo.gTime3": "Übergabe: 01.06.28",
  "bodo.samspillNote": "Zusammenarbeit (samspill) bedeutet, dass Bauherr und Unternehmer zuerst gemeinsam eine <b>Entwicklungsphase</b> durchlaufen — Lösungen optimieren, Unsicherheit quantifizieren und einen <b>Zielpreis</b> vereinbaren — bevor der Bau beginnt. Dort werden die grossen Weichen gestellt.",

  "org.eyebrow": "Werkzeug 1 · Organisation",
  "org.title": "Das <span class=\"g\">kreisförmige</span> Modell",
  "org.lead": "Wir haben den Organisationsplan im Detail gezeigt: interdisziplinäre Scrum-Teams rund um ein gemeinsames Zentrum, alle mit derselben Aufgabe — das Projekt als Ganzes zu optimieren. Keine Pyramide. Ein Kreis, in dem sich die Fachdisziplinen in der Mitte treffen.",
  "org.hub": "Interdisziplinäre<br>Kooperationsteams",
  "org.t1": "Rohbau",
  "org.t2": "Fassade & Dach",
  "org.t3": "Ausbau",
  "org.t4": "HLKSE / Technik",
  "org.t5": "Planung",
  "org.t6": "Beschaffung",
  "org.t7": "Produktion",
  "org.t8": "BIM / VDC",
  "org.caption": "Fahre über ein Team, um es hervorzuheben. Jedes Team besitzt seinen Bereich, arbeitet aber auf dasselbe Zentrum hin.",
  "embed.kicker": "Probiere es selbst",
  "embed.title": "Der Kern des VDC-Motors",
  "embed.lead": "Drei Dinge bilden den Kern des VDC-Motors. Klicke dich im interaktiven Modell unten durch jeden davon — oder öffne es im Vollbild.",
  "embed.open": "Im Vollbild öffnen",
  "embed.close": "Schliessen",
  "embed.p1L": "Organisation",
  "embed.p1": "Der Kreis, nicht die Pyramide. Das Projekt im Zentrum, mit interdisziplinären Teams darum herum — Entscheidungen fallen dort, wo die Arbeit geschieht.",
  "embed.p2L": "Planung & Takt",
  "embed.p2": "Ein gemeinsamer Takt für Planung, Produktion und systematische Fertigstellung — jedes Gewerk im selben Rhythmus.",
  "embed.p3L": "Kosten & Risiko",
  "embed.p3": "Die Kalkulation entwickelt sich mit dem Reifegrad, und das Risiko wird gesteuert, bevor es das Gebäude erreicht — hin zu einem Zielpreis, dem man vertrauen kann.",
  "embed.popen": "Modul öffnen",
  "embed.whyTitle": "Warum der Kreis die Pyramide schlägt",
  "embed.tradL": "Traditionelle Hierarchie",
  "embed.trad1": "Entscheidungen fallen oben — wer am meisten weiss, wird zuletzt gehört.",
  "embed.trad2": "Jede Fachdisziplin optimiert ihr eigenes Silo, nicht das Ganze.",
  "embed.trad3": "Informationen erreichen die Basis spät — Fehler zeigen sich auf der Baustelle.",
  "embed.trad4": "Lange Entscheidungswege bedeuten langsame Reaktion, wenn sich etwas ändert.",
  "embed.wheelL": "Das Kooperationsrad",
  "embed.wheel1": "Jedes Team arbeitet auf dasselbe Ziel im Zentrum hin.",
  "embed.wheel2": "Interdisziplinäre Entscheidungen fallen dort, wo die Arbeit geschieht.",
  "embed.wheel3": "Fachberater werden bei Bedarf hinzugezogen — die richtige Kompetenz zur richtigen Zeit.",
  "embed.wheel4": "Kurze Wege zwischen den Disziplinen ergeben eine schnelle, gemeinsame Reaktion.",

  "cost.eyebrow": "Werkzeug 2 · Kosten",
  "cost.title": "Kosten werden nach<br><span class=\"g\">zwei Prinzipien</span> entwickelt",
  "cost.lead": "Die Kosten im Projekt werden nicht geschätzt. Sie werden Entscheidung für Entscheidung entwickelt, indem man fragt, ob jede Lösung zwei Dinge tut:",
  "cost.p1L": "Risiko senken",
  "cost.p1": "Lösungen wählen, die Unsicherheit aus dem Projekt nehmen — was schiefgehen kann, kostet immer am meisten.",
  "cost.p2L": "Reifegrad erhöhen",
  "cost.p2": "Lösungen von der Skizze zur fertigen, entschiedenen Grundlage führen — Reifegrad macht einen Preis zu etwas, dem man vertrauen kann.",
  "cost.sum": "Und das Ganze summiert sich zu einer Konsequenz: <b>Zeit</b>. Senke das Risiko und erhöhe den Reifegrad, und der Zeitplan fügt sich. Tust du es nicht, zahlst du mit Zeit — und Zeit ist die teuerste Währung auf einer Baustelle.",

  "takt.eyebrow": "Werkzeug 3 · Fortschritt",
  "takt.title": "Zeitpläne als<br><span class=\"g\">Produktionssysteme</span> gebaut",
  "takt.lead": "In beiden Projekten ist der Zeitplan als Produktionssystem aufgebaut — Taktplanung und Taktsteuerung. Die Arbeit wird in gleich grosse Kontrollbereiche aufgeteilt, und «Züge» von Gewerken durchlaufen sie in festem Rhythmus: Beton, Zimmerei, Sanitär, Lüftung, Elektro — Wagen für Wagen.",
  "takt.legendArea": "Vertikal: Kontrollbereiche (Orte und Phasen)",
  "takt.legendTrain": "Horizontal: Zeit — Gewerke rücken pro Takt einen Ort weiter",
  "takt.cars": ["Beton","Zimmerei","Sanitär","Lüftung","Elektro"],
  "takt.locs": ["KB-01 · Fundament","KB-02 · Ebene 1","KB-03 · Ebene 2","KB-04 · Ebene 3","KB-05 · Dach & Technik","KB-06 · Fassade"],
  "takt.caption": "Ein vereinfachter Takt: Jedes Gewerk folgt dem vorherigen in festem Rhythmus durch die Kontrollbereiche. Vorhersehbar für alle — und leicht zu erkennen, wenn etwas ins Rutschen gerät.",
  "takt.note": "Beim A-Block waren Planung, der Vorbereitungszug und der Ausbauzug an denselben Takt gebunden, mit fertiger Arbeitsgrundlage sechs Wochen vor dem Start jedes Kontrollbereichs.",

  "people.eyebrow": "Das Wichtigste",
  "people.q": "Alle Methoden und alle Technologie sind nichts wert, wenn man die Menschen nicht mitnimmt. Sie sind IMMER das Wichtigste.",
  "people.body": "Beide Projekte legten starken Fokus auf Teamentwicklung und die Schulung der Menschen im Projekt. Es ist der Kontakt zwischen Menschen, der Projekte zum Entstehen bringt — und der Weltklasse-Projekte möglich macht. Modelle und Takt und Kalkulationen sind nur Werkzeuge. Der Wert liegt in den Händen und Köpfen, die sie nutzen.",

  "tools.eyebrow": "KI-Werkzeuge & unsere eigenen Werkzeuge",
  "tools.title": "Die Werkzeuge, die wir euch <span class=\"g\">gezeigt haben</span>",
  "tools.lead": "Wir haben einige unserer KI-Werkzeuge und unser eigenes Takt-Werkzeug vorgeführt. Hier sind die Links — probiert sie unbedingt selbst aus.",
  "tools.c1L": "Kostenlose digitale Werkzeuge",
  "tools.c1": "Acht kleine, kostenlose Werkzeuge, aufgebaut auf unserer langen Erfahrung — jedes löst ein konkretes Problem im Projektalltag.",
  "tools.c1cta": "Die digitalen Werkzeuge ansehen",
  "tools.c2L": "Taktplan",
  "tools.c2": "Unser eigenes Werkzeug für Taktplanung und -steuerung.",
  "tools.c2cta": "Taktplan öffnen",
  "tools.c3L": "Schon von VDC gehört?",
  "tools.c3": "Eine kurze, kostenlose Einführung in VDC — ein guter Anfang.",
  "tools.c3cta": "Den Kurs belegen",
  "tools.coursesL": "Schulungsprogramme",
  "tools.courses": "Unsere Kurse sind <b>kostenlos</b> und auf <b>Norwegisch, Englisch und Spanisch</b> verfügbar. Registriere dich und melde dich an (z. B. mit Google), dann kann es losgehen.",
  "tools.coursescta": "Alle Kurse ansehen",

  "about.eyebrow": "Über uns",
  "about.title": "Mit wem ihr den<br>Nachmittag <span class=\"g\">verbracht</span> habt",
  "about.lead": "Lean Communications ist eine kleine Beratung. Wir tun zwei Dinge: Wir entwickeln die Kompetenzen der Menschen in der Baubranche, und wir leiten komplexe Bauprojekte. Oft beides gleichzeitig — denn in den echten Projekten setzt sich die Kompetenz fest.",
  "about.c1L": "Kompetenzentwicklung",
  "about.c1": "Kurse, Schulungen und Coaching in Lean und VDC — für die ganze Organisation, nicht nur die Führung.",
  "about.c2L": "Projektleitung",
  "about.c2": "Wir steigen in echte, komplexe Bauprojekte ein und helfen ihnen, Lean und VDC in der Praxis umzusetzen.",
  "about.pmNum": "15",
  "about.pmNumL": "Projektleiter, 100% in echten Projekten",
  "about.pm1": "Darüber hinaus beschäftigen wir <b>15 Projektleiter</b>, die zu 100% in Projekten arbeiten — als Projektleiter, Planungsleiter, Terminplaner, Projektsteuerer, Kultur- und Teamentwickler und mehr.",
  "about.pmR1": "Projektleiter",
  "about.pmR2": "Planungsleiter",
  "about.pmR3": "Terminplaner",
  "about.pmR4": "Projektsteuerer",
  "about.pmR5": "Kultur- &amp; Teamentwickler",
  "about.pm2": "Durch diesen Kontakt mit echten Projekten bauen wir die Erfahrung und Kompetenz direkt in neue Schulungs- und Kompetenzprodukte ein — damit Projekte noch besser werden, in Norwegen wie im Ausland.",

  "cta.eyebrow": "Danke für den Besuch",
  "cta.title": "Viel Erfolg mit<br>Digitalem Bauen",
  "cta.lead": "Es war uns eine Freude, euch hier zu haben. Nehmt eine Sache mit: Die Werkzeuge sind für alle gleich — es sind die Menschen, die den Unterschied machen. Bleibt in Kontakt und meldet euch, wenn ihr wieder in Oslo seid. Das Bier steht bereit.",
  "cta.o1L": "Die Kurse",
  "cta.o1": "Kostenlos, in drei Sprachen. Beginnt mit «Schon von VDC gehört?».",
  "cta.o1f": "leancommunications.no",
  "cta.o2L": "Die Werkzeuge",
  "cta.o2": "Die Technologieseite und Taktplan — probiert sie an eurem eigenen Projekt.",
  "cta.o2f": "Digitale Werkzeuge",
  "cta.o3L": "Wir",
  "cta.o3": "Øyvind und der Rest der Lean-Communications-Crew.",
  "cta.o3f": "Kontakt aufnehmen",

  "footer.tag": "Norwegens grösster Anbieter von Lean- und VDC-Schulungen für die Baubranche. Partner der NTNU. Büros in Oslo und Bergen.",
  "footer.note": "Eine Zusammenfassung für MAS Digitales Bauen (FHNW) nach der VDC Innovation Week in Oslo, Juni 2026. Projektdaten vom A-Block K204 (Regierungsviertel) und Neuer Flughafen Bodø. Kunstwerk: AAhkA von Outi Pieski (KORO)."
}

};
